/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.Conexion;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Johnnatan
 */
public class Admin_Certificados extends javax.swing.JDialog {
    DefaultListModel listModel = new DefaultListModel();
    String cedula="";
    /**
     * Creates new form Admin_Certificados
     */
    public Admin_Certificados(java.awt.Frame parent, boolean modal, String ced) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        this.cedula=ced;
        cedula_emp.setText(ced);
        ////////////////////**************************************
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        table_cert_alt.getColumnModel().getColumn(0).setCellRenderer(tcr);
        table_cert_alt.getColumnModel().getColumn(1).setCellRenderer(tcr);
        table_protocol.getColumnModel().getColumn(0).setCellRenderer(tcr);
        table_riesgo.getColumnModel().getColumn(0).setCellRenderer(tcr);
        table_riesgo.getColumnModel().getColumn(1).setCellRenderer(tcr);
        //////////////////////************************************
        load_emp(ced);
        load_cert_alt(ced, table_cert_alt);
        load_curso_protocolo(ced, table_protocol);
        load_riesgo(ced, table_riesgo);
        load_list_riesgo();
    }
    public Admin_Certificados(javax.swing.JDialog parent, boolean modal, String ced) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        this.cedula=ced;
        cedula_emp.setText(ced);
        ////////////////////**************************************
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        table_cert_alt.getColumnModel().getColumn(0).setCellRenderer(tcr);
        table_cert_alt.getColumnModel().getColumn(1).setCellRenderer(tcr);
        table_protocol.getColumnModel().getColumn(0).setCellRenderer(tcr);
        table_riesgo.getColumnModel().getColumn(0).setCellRenderer(tcr);
        table_riesgo.getColumnModel().getColumn(1).setCellRenderer(tcr);
        ////////////////////**************************************
        load_emp(ced);
        load_cert_alt(ced, table_cert_alt);
        load_curso_protocolo(ced, table_protocol);
        load_riesgo(ced, table_riesgo);
        load_list_riesgo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu_alturas = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedula_emp = new javax.swing.JLabel();
        nombre_emp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_cert_alt = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        f_exam_cert_alt = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        f_cert = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_protocol = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        f_prot = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_riesgo = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        f_riesgo = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cb_riesgo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jMenuItem1.setText("Editar");
        jPopupMenu_alturas.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Certificados y Cursos");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Empleado"));

        jLabel3.setText("Cedula");

        jLabel4.setText("Nombre");

        cedula_emp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cedula_emp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cedula_emp.setText("cedula");

        nombre_emp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nombre_emp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_emp.setText("nombre");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cedula_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cedula_emp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombre_emp))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Certificados Trabajo en Alturas"));

        table_cert_alt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Examen", "Fecha Certificado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_cert_alt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table_cert_alt.setComponentPopupMenu(jPopupMenu_alturas);
        jScrollPane2.setViewportView(table_cert_alt);
        if (table_cert_alt.getColumnModel().getColumnCount() > 0) {
            table_cert_alt.getColumnModel().getColumn(0).setPreferredWidth(100);
            table_cert_alt.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_cert_alt.getColumnModel().getColumn(1).setHeaderValue("Fecha Certificado");
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Certificado Alturas"));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(258, 127));

        jLabel1.setText("Fecha Examen");

        jLabel2.setText("Fecha Certificado");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f_cert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_exam_cert_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(f_exam_cert_alt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(f_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Curso protocolo"));

        table_protocol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_protocol.setComponentPopupMenu(jPopupMenu_alturas);
        jScrollPane3.setViewportView(table_protocol);
        if (table_protocol.getColumnModel().getColumnCount() > 0) {
            table_protocol.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo curso protocolo"));
        jPanel6.setPreferredSize(new java.awt.Dimension(258, 127));

        jLabel5.setText("Fecha curso");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(f_prot, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(f_prot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Encuesta riesgo"));

        table_riesgo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Encuesta", "Riesgo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_riesgo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table_riesgo.setComponentPopupMenu(jPopupMenu_alturas);
        jScrollPane4.setViewportView(table_riesgo);
        if (table_riesgo.getColumnModel().getColumnCount() > 0) {
            table_riesgo.getColumnModel().getColumn(0).setPreferredWidth(100);
            table_riesgo.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo encuesta riesgo"));
        jPanel7.setPreferredSize(new java.awt.Dimension(258, 127));

        jLabel6.setText("Fecha encuesta");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Riesgo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_riesgo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(f_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (f_exam_cert_alt.getDate()!=null) {
            if (f_cert.getDate()!=null) {
                int conf = JOptionPane.showConfirmDialog(this,"Esta seguro que desea agregar la información del curso de altura?","Confirmación",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
                if (conf == JOptionPane.YES_OPTION) {
                        Conexion con = new Conexion();
                        ResultSet r;
                        con.conexion();
                    try {
                        r = con.s.executeQuery ("SELECT `FECHA_EXAM_CERT`, `FECHA_CERT`, `ID_EMP`, `SYNC_ARHI` FROM `t_cert_alturas` WHERE ID_EMP = "+cedula+" AND FECHA_CERT ='"+new SimpleDateFormat("yyyy-MM-dd").format(f_cert.getDate())+"'");
                        if(r.next()){
                            JOptionPane.showMessageDialog(null,"El certificado de alturas que intenta ingresar ya existe","Error",JOptionPane.ERROR_MESSAGE);
                        }else{
                            con.s.executeUpdate("INSERT INTO `t_cert_alturas`(`FECHA_EXAM_CERT`, `FECHA_CERT`, `ID_EMP`) VALUES ('"+new SimpleDateFormat("yyyy-MM-dd").format(f_exam_cert_alt.getDate())+"','"+new SimpleDateFormat("yyyy-MM-dd").format(f_cert.getDate())+"','"+cedula+"')");
                            JOptionPane.showMessageDialog(this,"El certificado de alturas fue ingresado correctamente","Información",JOptionPane.INFORMATION_MESSAGE);
                            load_cert_alt(cedula, table_cert_alt);
                        }
                        con.cerrar();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                        con.cerrar();
                        JOptionPane.showMessageDialog(null,ex,"Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null,"Ingrese una fecha de certificado en alturas valida","Error",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null,"Ingrese una fecha de examen del certificado en alturas valida","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (f_prot.getDate()!=null) {
            int conf = JOptionPane.showConfirmDialog(this,"Esta seguro que desea agregar la información del curso de protocolo?","Confirmación",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (conf == JOptionPane.YES_OPTION) {
                    Conexion con = new Conexion();
                    ResultSet r;
                    con.conexion();
                try {
                    r = con.s.executeQuery ("SELECT * FROM `t_cap_prot` WHERE ID_EMP = "+cedula+" AND FECHA_CAP_PROT ='"+new SimpleDateFormat("yyyy-MM-dd").format(f_prot.getDate())+"'");
                    if(r.next()){
                        JOptionPane.showMessageDialog(null,"El curso de protocolo que intenta ingresar ya existe","Error",JOptionPane.ERROR_MESSAGE);
                    }else{
                        con.s.executeUpdate("INSERT INTO `t_cap_prot`(`FECHA_CAP_PROT`, `ID_EMP`) VALUES ('"+new SimpleDateFormat("yyyy-MM-dd").format(f_prot.getDate())+"','"+cedula+"')");
                        JOptionPane.showMessageDialog(this,"La capacitacion de protocolo fue ingresada correctamente","Información",JOptionPane.INFORMATION_MESSAGE);
                        load_curso_protocolo(cedula, table_protocol);
                    }
                    con.cerrar();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    con.cerrar();
                    JOptionPane.showMessageDialog(null,ex,"Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null,"Ingrese una fecha de capacitacion de protocolo valida","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (f_riesgo.getDate()!=null) {
            if (!cb_riesgo.getSelectedItem().equals("Seleccione..")) {
                int conf = JOptionPane.showConfirmDialog(this,"Esta seguro que desea agregar la información de la encuesta de riesgo?","Confirmación",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
                if (conf == JOptionPane.YES_OPTION) {
                        Conexion con = new Conexion();
                        ResultSet r;
                        con.conexion();
                    try {
                        r = con.s.executeQuery ("SELECT * FROM `t_riesgo` WHERE ID_EMP = "+cedula+" AND FECHA_ENC ='"+new SimpleDateFormat("yyyy-MM-dd").format(f_riesgo.getDate())+"'");
                        if(r.next()){
                            JOptionPane.showMessageDialog(null,"La encuesta de riesgo que intenta ingresar ya existe","Error",JOptionPane.ERROR_MESSAGE);
                        }else{
                            con.s.executeUpdate("INSERT INTO `t_riesgo`(`FECHA_ENC`, `ID_EMP`, `ID_TIPO`) VALUES ('"+new SimpleDateFormat("yyyy-MM-dd").format(f_riesgo.getDate())+"','"+cedula+"', (SELECT ID_TIPO FROM t_tip_riesgo WHERE NOMBRE_TIPO = '"+cb_riesgo.getSelectedItem()+"'))");
                            JOptionPane.showMessageDialog(this,"La capacitacion de protocolo fue ingresada correctamente","Información",JOptionPane.INFORMATION_MESSAGE);
                            load_riesgo(cedula, table_riesgo);
                        }
                        con.cerrar();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                        con.cerrar();
                        JOptionPane.showMessageDialog(null,ex,"Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null,"Seleccione un tipo de riesgo valido","Error",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null,"Ingrese una fecha de encuesta valida","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Certificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Certificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Certificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Certificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin_Certificados dialog = new Admin_Certificados(new javax.swing.JFrame(), true, new String());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_riesgo;
    private javax.swing.JLabel cedula_emp;
    private com.toedter.calendar.JDateChooser f_cert;
    private com.toedter.calendar.JDateChooser f_exam_cert_alt;
    private com.toedter.calendar.JDateChooser f_prot;
    private com.toedter.calendar.JDateChooser f_riesgo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu_alturas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nombre_emp;
    private javax.swing.JTable table_cert_alt;
    private javax.swing.JTable table_protocol;
    private javax.swing.JTable table_riesgo;
    // End of variables declaration//GEN-END:variables
private void load_cert_alt(String c, JTable t){
    clear_table(t);
    DefaultTableModel modelo = (DefaultTableModel)t.getModel();
    Object [] fila = new Object[2];
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "`t_cert_alturas`\n" +
                                "WHERE ID_EMP = "+c+" ORDER BY FECHA_CERT DESC;");
        while(r.next()){
            modelo.addRow(fila);
            modelo.setValueAt(new SimpleDateFormat("dd-MM-yyyy").format(new SimpleDateFormat("yyyy-MM-dd").parse(r.getString("FECHA_EXAM_CERT"))),t.getRowCount()-1,0);
            modelo.setValueAt(new SimpleDateFormat("dd-MM-yyyy").format(new SimpleDateFormat("yyyy-MM-dd").parse(r.getString("FECHA_CERT"))),t.getRowCount()-1,1);
        }
        con.cerrar();
    }catch(ParseException | SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }   
}
private void load_curso_protocolo(String c, JTable t){
    clear_table(t);
    DefaultTableModel modelo = (DefaultTableModel)t.getModel();
    Object [] fila = new Object[2];
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "`t_cap_prot`\n" +
                                "WHERE ID_EMP = "+c+" ORDER BY FECHA_CAP_PROT DESC;");
        while(r.next()){
            modelo.addRow(fila);
            modelo.setValueAt(new SimpleDateFormat("dd-MM-yyyy").format(new SimpleDateFormat("yyyy-MM-dd").parse(r.getString("FECHA_CAP_PROT"))),t.getRowCount()-1,0);
        }
        con.cerrar();
    }catch(ParseException | SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
private void load_riesgo(String c, JTable t){
    clear_table(t);
    DefaultTableModel modelo = (DefaultTableModel)t.getModel();
    Object [] fila = new Object[2];
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    `t_riesgo`\n" +
                                "    INNER JOIN `t_tip_riesgo` \n" +
                                "        ON (`t_riesgo`.`ID_TIPO` = `t_tip_riesgo`.`ID_TIPO`)\n" +
                                "WHERE ID_EMP = "+c+" ORDER BY FECHA_ENC DESC;");
        while(r.next()){
            modelo.addRow(fila);
            modelo.setValueAt(new SimpleDateFormat("dd-MM-yyyy").format(new SimpleDateFormat("yyyy-MM-dd").parse(r.getString("FECHA_ENC"))),t.getRowCount()-1,0);
            modelo.setValueAt(r.getString("NOMBRE_TIPO"),t.getRowCount()-1,1);
        }
        con.cerrar();
    }catch(ParseException | SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
private void clear_table(JTable t){
    DefaultTableModel modelo = (DefaultTableModel)t.getModel();
    while(t.getRowCount()!=0){
        modelo.removeRow(t.getRowCount()-1);
    }
    t.setModel(modelo);
}
private void load_emp(String c){
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "`t_empleados`\n" +
                                "WHERE ID_EMP = "+c);
        if(r.next()){
            String nombre1 = r.getString("NOMBRE_1_EMP");
            String nombre2 = r.getString("NOMBRE_2_EMP");
            String apellido1 = r.getString("APELLIDO_1_EMP");
            String apellido2 = r.getString("APELLIDO_2_EMP");
            nombre1=nombre1+" ";
            apellido1=apellido1+" ";
            if (!nombre2.equals("")) {
                nombre2+=" ";
            }
            if (!apellido2.equals("")) {
                apellido2+=" ";
            }
            cedula_emp.setText(r.getString("ID_EMP"));
            nombre_emp.setText(nombre1+nombre2+apellido1+apellido2);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    } 
}
private void load_list_riesgo(){
    cb_riesgo.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    `t_tip_riesgo`");
        while(r.next()){
            cb_riesgo.addItem(r.getString("NOMBRE_TIPO"));
            
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
}
