/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.AutoCompletion;
import com.jm.Edicof.Clases.Conexion;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JHONN
 */
public class Admin_Subcontratistas extends javax.swing.JDialog {
    static DefaultTableModel modelo = new DefaultTableModel();
    Object [] fila = new Object[7];
    String nit="";
    /**
     * Creates new form Admin_Subcontratistas
     */
    int col_nit_contr =0;
    int col_contr =1;
    int col_obra = 2;
    int col_f_ini = 3;
    int col_f_fin = 4;
    int col_contrato = 5;
    int col_actividad = 6;
    public Admin_Subcontratistas(java.awt.Frame parent, boolean modal, String nit) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        this.nit=nit;
        modelo = (DefaultTableModel)subcontratistas.getModel(); 
        ac_nit(cb_nit_sub);
        ac_nit(cb_nit_contr);
        ac_obra(cb_obra);
        nit_empresa.setText(nit);
        cb_nit_sub.setSelectedItem(nit);
        ////////////////////**************************************
        //*********************************
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < subcontratistas.getColumnCount(); i++) {
            subcontratistas.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        //////////////////////************************************
        nombre_empresa.setText(load_empresa(nit));
        clear_sub();
        load_sub(cb_nit_sub.getSelectedItem().toString());
    }
    public Admin_Subcontratistas(javax.swing.JDialog parent, boolean modal, String nit) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        this.nit=nit;
        modelo = (DefaultTableModel)subcontratistas.getModel(); 
        ac_nit(cb_nit_sub);
        ac_nit(cb_nit_contr);
        ac_obra(cb_obra);
        nit_empresa.setText(nit);
        cb_nit_sub.setSelectedItem(nit);
        ////////////////////**************************************
        //*********************************
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < subcontratistas.getColumnCount(); i++) {
            subcontratistas.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        //////////////////////************************************
        nombre_empresa.setText(load_empresa(nit));
        clear_sub();
        load_sub(cb_nit_sub.getSelectedItem().toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subcontratistas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cb_nit_sub = new javax.swing.JComboBox<>();
        cb_nit_contr = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_obra = new javax.swing.JComboBox<>();
        f_ini = new com.toedter.calendar.JDateChooser();
        f_fin = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        contrato = new javax.swing.JTextField();
        actividad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nit_empresa = new javax.swing.JLabel();
        nombre_empresa = new javax.swing.JLabel();

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jPopupMenu1.getAccessibleContext().setAccessibleParent(subcontratistas);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Sub Contratistas");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Información Contratistas"));

        subcontratistas.setAutoCreateRowSorter(true);
        subcontratistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nit Contratista", "Contratista", "Obra", "F Inicio", "F Final", "Contrato", "Funcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        subcontratistas.setToolTipText("Click derecho para mas opciones");
        subcontratistas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        subcontratistas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(subcontratistas);
        if (subcontratistas.getColumnModel().getColumnCount() > 0) {
            subcontratistas.getColumnModel().getColumn(0).setMinWidth(120);
            subcontratistas.getColumnModel().getColumn(0).setPreferredWidth(120);
            subcontratistas.getColumnModel().getColumn(0).setMaxWidth(120);
            subcontratistas.getColumnModel().getColumn(1).setMinWidth(450);
            subcontratistas.getColumnModel().getColumn(1).setPreferredWidth(450);
            subcontratistas.getColumnModel().getColumn(1).setMaxWidth(450);
            subcontratistas.getColumnModel().getColumn(2).setMinWidth(250);
            subcontratistas.getColumnModel().getColumn(2).setPreferredWidth(250);
            subcontratistas.getColumnModel().getColumn(2).setMaxWidth(250);
            subcontratistas.getColumnModel().getColumn(3).setMinWidth(120);
            subcontratistas.getColumnModel().getColumn(3).setPreferredWidth(120);
            subcontratistas.getColumnModel().getColumn(3).setMaxWidth(120);
            subcontratistas.getColumnModel().getColumn(4).setMinWidth(120);
            subcontratistas.getColumnModel().getColumn(4).setPreferredWidth(120);
            subcontratistas.getColumnModel().getColumn(4).setMaxWidth(120);
            subcontratistas.getColumnModel().getColumn(5).setMinWidth(180);
            subcontratistas.getColumnModel().getColumn(5).setPreferredWidth(180);
            subcontratistas.getColumnModel().getColumn(5).setMaxWidth(180);
            subcontratistas.getColumnModel().getColumn(6).setMinWidth(500);
            subcontratistas.getColumnModel().getColumn(6).setPreferredWidth(500);
            subcontratistas.getColumnModel().getColumn(6).setMaxWidth(500);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Registro"));

        jLabel3.setText("Nit Sub contratista");

        AutoCompletion.enable(cb_nit_sub);
        cb_nit_sub.setEditable(true);
        cb_nit_sub.setEnabled(false);

        AutoCompletion.enable(cb_nit_contr);
        cb_nit_contr.setEditable(true);

        jLabel5.setText("Nit Contratista");

        jLabel10.setText("Obra");

        AutoCompletion.enable(cb_obra);
        cb_obra.setEditable(true);

        jLabel6.setText("F Inicio");

        jLabel8.setText("F Final");

        jLabel1.setText("Contrato");

        contrato.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        actividad.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel2.setText("Actividad");

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btn_add.setText("Agregar");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_nit_sub, 0, 195, Short.MAX_VALUE)
                            .addComponent(cb_nit_contr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(f_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(f_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(cb_obra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(actividad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_add)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(f_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(f_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_nit_contr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cb_obra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_nit_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btn_add)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empresa"));

        jLabel4.setText("NIT");

        jLabel7.setText("Nombre");

        nit_empresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nit_empresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nit_empresa.setText("nit");

        nombre_empresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nombre_empresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_empresa.setText("nombre_empresa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nit_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(nit_empresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(nombre_empresa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if (!cb_nit_sub.getSelectedItem().equals("Seleccione..")) {
            if (!cb_nit_contr.getSelectedItem().equals("Seleccione..")) {
                if (!cb_nit_sub.getSelectedItem().equals(cb_nit_contr.getSelectedItem())) {
                    if (f_ini!=null) {
                        if (f_ini!=null) {
                            if (!contrato.getText().equals("")) {
                                if (!cb_obra.getSelectedItem().equals("Seleccione..")) {
                                    if (!actividad.getText().equals("")) {
                                        int conf = JOptionPane.showConfirmDialog(this,"Esta seguro que desea agregar la información del Subcontratista?","Confirmación",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
                                        if (conf == JOptionPane.YES_OPTION) {
                                            Conexion con = new Conexion();
                                            ResultSet r;
                                            con.conexion();
                                            try {
                                                r = con.s.executeQuery ("SELECT * FROM `t_rel_subcontratista` WHERE ID_CONTR = '"+cb_nit_contr.getSelectedItem()+"' AND ID_SUBCONTR = '"+cb_nit_sub.getSelectedItem()+"'");
                                                if(r.next()){
                                                    JOptionPane.showMessageDialog(null,"El registro del subcontratista que desea ingresar ya existe","Error",JOptionPane.ERROR_MESSAGE);
                                                }else{
                                                    con.s.executeUpdate("INSERT INTO `t_rel_subcontratista`\n" +
                                                                        "            (`ID_CONTR`,\n" +
                                                                        "             `ID_SUBCONTR`,\n" +
                                                                        "             `ID_OBRA`,\n" +
                                                                        "             `F_INICIO`,\n" +
                                                                        "             `F_FINAL`,\n" +
                                                                        "             `CONTRATO`,\n" +
                                                                        "             `FUNCION`)\n" +
                                                                        "VALUES ('"+cb_nit_contr.getSelectedItem()+"',\n" +
                                                                        "        '"+cb_nit_sub.getSelectedItem()+"',\n" +
                                                                        "        "+get_id_obra(cb_obra.getSelectedItem())+",\n" +
                                                                        "        '"+new SimpleDateFormat("yyy-MM-dd").format(f_ini.getDate())+"',\n" +
                                                                        "        '"+new SimpleDateFormat("yyy-MM-dd").format(f_fin.getDate())+"',\n" +
                                                                        "        '"+contrato.getText()+"',\n" +
                                                                        "        '"+actividad.getText()+"');");
                                                    JOptionPane.showMessageDialog(this,"El registro del subcontratista fue ingresado correctamente","Información",JOptionPane.INFORMATION_MESSAGE);
                                                    clear_sub();
                                                    load_sub(cb_nit_sub.getSelectedItem().toString());
                                                    //load_cert_alt(cedula, table_cert_alt);
                                                }
                                                con.cerrar();
                                            } catch (SQLException ex) {
                                                ex.printStackTrace();
                                                con.cerrar();
                                                JOptionPane.showMessageDialog(null,ex,"Error",JOptionPane.ERROR_MESSAGE);
                                            }
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null,"Ingrese la descripcion de la actividad a realizar por el Subcontratista","Error",JOptionPane.ERROR_MESSAGE);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null,"Seleccione una obra valida","Error",JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(null,"Ingrese un numero de contrato valido","Error",JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null,"Seleccione una fecha de fin valida","Error",JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null,"Seleccione una fecha de inicio valida","Error",JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null,"Asegurese que el Nit del Contratista y del Subcontratista sean diferentes.","Error",JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null,"Seleccione el NIT del Contratista","Error",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null,"Seleccione el NIT del Subcontratista","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (subcontratistas.getSelectedRow()!=-1) {
            int conf = JOptionPane.showConfirmDialog(this,"Esta seguro que desea eliminar la información del Subcontratista?","Confirmación",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (conf == JOptionPane.YES_OPTION) {
                Conexion con = new Conexion();
                ResultSet r;
                con.conexion();
                try {
                    con.s.executeUpdate("DELETE\n" +
                                        "FROM `t_rel_subcontratista`\n" +
                                        "WHERE `ID_CONTR` = '"+subcontratistas.getValueAt(subcontratistas.getSelectedRow(), col_nit_contr)+"'\n" +
                                        "    AND `ID_SUBCONTR` = '"+cb_nit_sub.getSelectedItem()+"';");
                    JOptionPane.showMessageDialog(this,"El registro del subcontratista fue eliminado correctamente","Información",JOptionPane.INFORMATION_MESSAGE);
                    clear_sub();
                    load_sub(cb_nit_sub.getSelectedItem().toString());
                    //load_cert_alt(cedula, table_cert_alt);
                    con.cerrar();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    con.cerrar();
                    JOptionPane.showMessageDialog(null,ex,"Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            
        } else {
            JOptionPane.showMessageDialog(this,"Debe seleccionar al menos un registro.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Subcontratistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Subcontratistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Subcontratistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Subcontratistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin_Subcontratistas dialog = new Admin_Subcontratistas(new javax.swing.JFrame(), true, new String(""));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actividad;
    private javax.swing.JButton btn_add;
    private javax.swing.JComboBox<String> cb_nit_contr;
    private javax.swing.JComboBox<String> cb_nit_sub;
    private javax.swing.JComboBox<String> cb_obra;
    private javax.swing.JTextField contrato;
    private com.toedter.calendar.JDateChooser f_fin;
    private com.toedter.calendar.JDateChooser f_ini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nit_empresa;
    private javax.swing.JLabel nombre_empresa;
    private javax.swing.JTable subcontratistas;
    // End of variables declaration//GEN-END:variables
private String load_empresa(String nit){
    String ret="";
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "`t_empresas`\n" +
                                "WHERE ID_EMPRESA = "+nit);
        if(r.next()){
            ret = r.getString("NOMBRE_EMPRESA");
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    } 
    return ret;
}
private static void ac_nit(JComboBox cb){
    cb.removeAllItems();
    cb.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_EMPRESAS ORDER BY ID_EMPRESA ASC;");
        while(r.next()){
            String str=r.getString("ID_EMPRESA");
            cb.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
private static void ac_obra(JComboBox cb){
    cb.removeAllItems();
    cb.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_OBRA ORDER BY NOMBRE_OBRA ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_OBRA");
            cb.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
private String get_id_obra(Object obra){
    String i = "";
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_obra\n" +
                                "WHERE NOMBRE_OBRA='"+obra+"';");
        if(r.next()){
            i = r.getString("ID_OBRA");
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
    }
    return i;
}
private void load_sub(String n){
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    `t_rel_subcontratista`\n" +
                                "    INNER JOIN `t_obra` \n" +
                                "        ON (`t_rel_subcontratista`.`ID_OBRA` = `t_obra`.`ID_OBRA`)\n" +
                                "    INNER JOIN `t_empresas` \n" +
                                "        ON (`t_rel_subcontratista`.`ID_CONTR` = `t_empresas`.`ID_EMPRESA`)\n" +
                                "WHERE ID_SUBCONTR='"+n+"';");
        while(r.next()){
            modelo.addRow(fila);
            subcontratistas.setModel(modelo);
            modelo.setValueAt(r.getString("ID_EMPRESA"), subcontratistas.getRowCount()-1, col_nit_contr);
            modelo.setValueAt(r.getString("NOMBRE_EMPRESA"), subcontratistas.getRowCount()-1, col_contr);
            modelo.setValueAt(r.getString("NOMBRE_OBRA"), subcontratistas.getRowCount() - 1, col_obra);
            modelo.setValueAt(r.getString("F_INICIO"), subcontratistas.getRowCount() - 1, col_f_ini);
            modelo.setValueAt(r.getString("F_FINAL"), subcontratistas.getRowCount() - 1, col_f_fin);
            modelo.setValueAt(r.getString("CONTRATO"), subcontratistas.getRowCount() - 1, col_contrato);
            modelo.setValueAt(r.getString("FUNCION"), subcontratistas.getRowCount() - 1, col_actividad);
            
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
    }
}
private void clear_sub(){
    modelo = (DefaultTableModel)subcontratistas.getModel(); 
    while(subcontratistas.getRowCount()!=0){
        modelo.removeRow(subcontratistas.getRowCount()-1);
    }
    subcontratistas.setModel(modelo);
}
}
