/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.AutoCompletion;
import com.jm.Edicof.Clases.Conexion;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Buscar_Empresa extends javax.swing.JDialog {
DefaultTableModel modelo;
TextAutoCompleter tac_empleador = null;
TextAutoCompleter tac_arl = null;
TextAutoCompleter tac_ccf = null;
TextAutoCompleter tac_actividad = null;
TextAutoCompleter tac_obra = null;
Object [] fila = new Object[11];
    /**
     * Creates new form Buscar_Empresa
     */
    public Buscar_Empresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        init();
        ac_nit();
        ac_empleador();
        ac_arl();
        ac_ccf();
        ac_obra();
        ac_acividad();
        tac_empleador.setMode(0);
        tac_obra.setMode(0);
        tac_arl.setMode(0);
        tac_ccf.setMode(0);
        tac_actividad.setMode(0);
        clear_empresas();
    }
    public void init(){
        tac_empleador = new TextAutoCompleter(t_empleador);
        tac_arl = new TextAutoCompleter(tf_arl);
        tac_ccf = new TextAutoCompleter(tf_ccf);
        tac_obra = new TextAutoCompleter(tf_obra);
        tac_actividad = new TextAutoCompleter(actividad);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cb_nit = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        t_empleador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_obra = new javax.swing.JTextField();
        tf_arl = new javax.swing.JTextField();
        tf_ccf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        actividad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        empresas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        n_empresas = new javax.swing.JLabel();

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        jMenuItem2.setText("Visualizar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem1.setText("Editar Empresa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar empresa");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterio de busqueda"));

        cb_nit.setEditable(true);
        AutoCompletion.enable(cb_nit);

        jLabel1.setText("Nit");

        jLabel2.setText("Nombre");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table_tab_search.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filter_delete.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        t_empleador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setText("Obra");

        jLabel11.setText("ARL");

        jLabel12.setText("CCF");

        tf_obra.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf_arl.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf_ccf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Actividad");

        actividad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cb_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_empleador, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_obra, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tf_ccf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_arl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cb_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(t_empleador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tf_arl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(tf_obra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tf_ccf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de la busqueda"));
        jPanel3.setPreferredSize(new java.awt.Dimension(484, 267));

        empresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nit", "Nombre Empresa", "ARL", "CCF", "Correo Interno", "Habilitar Interno", "Correo Contratista 1", "Habilitar Correo 1", "Correo Contratista 2", "Habilitar Correo 2", "Correo Contratista 3", "Habilitar Correo 3", "Representante Legal", "Telefonos", "Actividad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empresas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        empresas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(empresas);
        if (empresas.getColumnModel().getColumnCount() > 0) {
            empresas.getColumnModel().getColumn(0).setMinWidth(80);
            empresas.getColumnModel().getColumn(0).setPreferredWidth(80);
            empresas.getColumnModel().getColumn(0).setMaxWidth(80);
            empresas.getColumnModel().getColumn(1).setMinWidth(250);
            empresas.getColumnModel().getColumn(1).setPreferredWidth(250);
            empresas.getColumnModel().getColumn(1).setMaxWidth(250);
            empresas.getColumnModel().getColumn(2).setMinWidth(150);
            empresas.getColumnModel().getColumn(2).setPreferredWidth(150);
            empresas.getColumnModel().getColumn(2).setMaxWidth(150);
            empresas.getColumnModel().getColumn(3).setMinWidth(150);
            empresas.getColumnModel().getColumn(3).setPreferredWidth(150);
            empresas.getColumnModel().getColumn(3).setMaxWidth(150);
            empresas.getColumnModel().getColumn(4).setMinWidth(250);
            empresas.getColumnModel().getColumn(4).setPreferredWidth(250);
            empresas.getColumnModel().getColumn(4).setMaxWidth(250);
            empresas.getColumnModel().getColumn(5).setMinWidth(80);
            empresas.getColumnModel().getColumn(5).setPreferredWidth(80);
            empresas.getColumnModel().getColumn(5).setMaxWidth(80);
            empresas.getColumnModel().getColumn(6).setMinWidth(250);
            empresas.getColumnModel().getColumn(6).setPreferredWidth(250);
            empresas.getColumnModel().getColumn(6).setMaxWidth(250);
            empresas.getColumnModel().getColumn(7).setMinWidth(80);
            empresas.getColumnModel().getColumn(7).setPreferredWidth(80);
            empresas.getColumnModel().getColumn(7).setMaxWidth(80);
            empresas.getColumnModel().getColumn(8).setMinWidth(250);
            empresas.getColumnModel().getColumn(8).setPreferredWidth(250);
            empresas.getColumnModel().getColumn(8).setMaxWidth(250);
            empresas.getColumnModel().getColumn(9).setMinWidth(80);
            empresas.getColumnModel().getColumn(9).setPreferredWidth(80);
            empresas.getColumnModel().getColumn(9).setMaxWidth(80);
            empresas.getColumnModel().getColumn(10).setMinWidth(250);
            empresas.getColumnModel().getColumn(10).setPreferredWidth(250);
            empresas.getColumnModel().getColumn(10).setMaxWidth(250);
            empresas.getColumnModel().getColumn(11).setMinWidth(80);
            empresas.getColumnModel().getColumn(11).setPreferredWidth(80);
            empresas.getColumnModel().getColumn(11).setMaxWidth(80);
            empresas.getColumnModel().getColumn(12).setMinWidth(250);
            empresas.getColumnModel().getColumn(12).setPreferredWidth(250);
            empresas.getColumnModel().getColumn(12).setMaxWidth(250);
            empresas.getColumnModel().getColumn(13).setMinWidth(150);
            empresas.getColumnModel().getColumn(13).setPreferredWidth(150);
            empresas.getColumnModel().getColumn(13).setMaxWidth(150);
            empresas.getColumnModel().getColumn(14).setMinWidth(150);
            empresas.getColumnModel().getColumn(14).setPreferredWidth(150);
            empresas.getColumnModel().getColumn(14).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

        jLabel7.setText("Numero de Empresas");

        n_empresas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n_empresas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n_empresas.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(n_empresas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(n_empresas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clear_empresas();
        //System.out.println(query(cb_nit, t_empleador, tf_obra, tf_arl, tf_ccf,actividad));
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try {
            r = con.s.executeQuery (query(cb_nit, t_empleador, tf_obra, tf_arl, tf_ccf,actividad));
            while (r.next()) {
                modelo.addRow(fila);
                //novedades.setModel(modelo);
                modelo.setValueAt(r.getString("ID_EMPRESA"),empresas.getRowCount()-1,0);
                modelo.setValueAt(r.getString("NOMBRE_EMPRESA"),empresas.getRowCount()-1,1);
                modelo.setValueAt(r.getString("NOMBRE_ARL"),empresas.getRowCount()-1,2);
                modelo.setValueAt(r.getString("NOMBRE_CCF"),empresas.getRowCount()-1,3);
                modelo.setValueAt(r.getString("CORREO_INTERNO"),empresas.getRowCount()-1,4);
                if (r.getInt("ENABLE_INTERNO")==1) {
                    modelo.setValueAt("SI",empresas.getRowCount()-1,5);
                }else{
                    modelo.setValueAt("NO",empresas.getRowCount()-1,5);
                } 
                modelo.setValueAt(r.getString("CORREO_CONTRATISTA_1"),empresas.getRowCount()-1,6);
                if (r.getInt("ENABLE_1")==1) {
                    modelo.setValueAt("SI",empresas.getRowCount()-1,7);
                }else{
                    modelo.setValueAt("NO",empresas.getRowCount()-1,7);
                }
                modelo.setValueAt(r.getString("CORREO_CONTRATISTA_2"),empresas.getRowCount()-1,8);
                if (r.getInt("ENABLE_2")==1) {
                    modelo.setValueAt("SI",empresas.getRowCount()-1,9);
                }else{
                    modelo.setValueAt("NO",empresas.getRowCount()-1,9);
                }
                modelo.setValueAt(r.getString("CORREO_CONTRATISTA_3"),empresas.getRowCount()-1,10);
                if (r.getInt("ENABLE_3")==1) {
                    modelo.setValueAt("SI",empresas.getRowCount()-1,11);
                }else{
                    modelo.setValueAt("NO",empresas.getRowCount()-1,11);
                }
                modelo.setValueAt(r.getString("REPRESENTANTE_LEGAL"),empresas.getRowCount()-1,12);
                modelo.setValueAt(r.getString("TELEFONOS"),empresas.getRowCount()-1,13);
                modelo.setValueAt(r.getString("NOMBRE_ACTIVIDAD"),empresas.getRowCount()-1,14);
            }
            n_empresas.setText(String.valueOf(empresas.getRowCount()));
            con.cerrar();
        }catch (SQLException e) {
            con.cerrar();
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,e,"Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cb_nit.setSelectedItem("Seleccione..");
        t_empleador.setText("");
        tf_obra.setText("");
        tf_arl.setText("");
        tf_ccf.setText("");
        actividad.setText("");
        clear_empresas();
        n_empresas.setText(String.valueOf(empresas.getRowCount()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (empresas.getSelectedRow()!=-1) {
            Edd_Empresa edd_empresa = new Edd_Empresa(this, true, empresas.getValueAt(empresas.getSelectedRow(),0).toString());
            edd_empresa.setLocationRelativeTo(this);
            edd_empresa.setVisible(true);
            jButton1ActionPerformed(evt);   
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar un registro para editarlo","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (empresas.getSelectedRow()!=-1) {
            View_Empresa view_empresa = new View_Empresa(this, true, empresas.getValueAt(empresas.getSelectedRow(),0).toString());
            view_empresa.setLocationRelativeTo(this);
            view_empresa.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar un registro para visualizarlo","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Buscar_Empresa dialog = new Buscar_Empresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actividad;
    private javax.swing.JComboBox<String> cb_nit;
    private javax.swing.JTable empresas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel n_empresas;
    private javax.swing.JTextField t_empleador;
    private javax.swing.JTextField tf_arl;
    private javax.swing.JTextField tf_ccf;
    private javax.swing.JTextField tf_obra;
    // End of variables declaration//GEN-END:variables
public void clear_empresas(){
    modelo = (DefaultTableModel)empresas.getModel(); 
    while(empresas.getRowCount()!=0){
        modelo.removeRow(empresas.getRowCount()-1);
    }
    empresas.setModel(modelo);
}
public void ac_nit(){
    cb_nit.removeAllItems();
    cb_nit.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_EMPRESAS ORDER BY NOMBRE_EMPRESA ASC;");
        while(r.next()){
            String str=r.getString("ID_EMPRESA");
            cb_nit.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public void ac_empleador(){
    tac_empleador.removeAllItems();
    tac_empleador.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_EMPRESAS ORDER BY NOMBRE_EMPRESA ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_EMPRESA");
            tac_empleador.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public void ac_arl(){
    tac_arl.removeAllItems();
    tac_arl.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_ARL ORDER BY NOMBRE_ARL ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_ARL");
            tac_arl.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public void ac_ccf(){
    tac_ccf.removeAllItems();
    tac_ccf.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_CCF ORDER BY NOMBRE_CCF ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_CCF");
            tac_ccf.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public void ac_obra(){
    tac_obra.removeAllItems();
    tac_obra.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_OBRA ORDER BY NOMBRE_OBRA ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_OBRA");
            tac_obra.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public void ac_acividad(){
    tac_actividad.removeAllItems();
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_ACTIVIDADES ORDER BY NOMBRE_ACTIVIDAD ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_ACTIVIDAD");
            tac_actividad.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public String query (javax.swing.JComboBox nit, javax.swing.JTextField empleador,javax.swing.JTextField obra, javax.swing.JTextField arl, javax.swing.JTextField ccf, javax.swing.JTextField actividad){
    String str_nit = "";
    String str_empleador = "";
    String str_obra= "";
    String str_arl= "";
    String str_ccf= "";
    String str_actividad= "";
    String str_query =  "SELECT *\n" +
                        "FROM\n" +
                        "    t_empresas\n" +
                        "    INNER JOIN t_arl \n" +
                        "        ON (t_empresas.ID_ARL = t_arl.ID_ARL)\n" +
                        "    INNER JOIN t_ccf \n" +
                        "        ON (t_empresas.ID_CCF = t_ccf.ID_CCF)\n" +
                        "    INNER JOIN t_actividades \n" +
                        "        ON (t_empresas.ID_ACTIVIDAD = t_actividades.ID_ACTIVIDAD)\n";
    if (!nit.getSelectedItem().equals("Seleccione..") ) {
        str_nit = "t_empresas.ID_EMPRESA = '"+nit.getSelectedItem()+"'";
    }else{
        str_nit = " ";
    }
    if (!empleador.getText().equals("") & !empleador.getText().equals(" ")) {
        str_empleador = "t_empresas.NOMBRE_EMPRESA='"+empleador.getText()+"'";
    }else{
        str_empleador =" ";
    }
//    if (!obra.getText().equals("") & !obra.getText().equals(" ")) {
//        str_obra = "t_obra.NOMBRE_OBRA='"+obra.getText()+"'";
//    }else{
//        str_obra =" ";
//    }
    if (!arl.getText().equals("") & !arl.getText().equals(" ")) {
        str_arl = "t_arl.NOMBRE_ARL='"+arl.getText()+"'";
    }else{
        str_arl =" ";
    }
    if (!ccf.getText().equals("") & !ccf.getText().equals(" ")) {
        str_ccf = "t_ccf.NOMBRE_CCF='"+ccf.getText()+"'";
    }else{
        str_ccf =" ";
    }
    if (!actividad.getText().equals("") & !actividad.getText().equals(" ")) {
        str_actividad = "t_actividades.NOMBRE_ACTIVIDAD='"+actividad.getText()+"'";
    }else{
        str_actividad =" ";
    }
//    if (!str_cedula.equals(" ") | !str_empleador.equals(" ") | !str_municipio.equals(" ") | !str_obra.equals(" ") | !str_eps.equals(" ") | !str_afp.equals(" ") | !str_arl.equals(" ") | !str_ccf.equals(" ") | !str_tipo.equals(" ") | !str_date.equals(" ")) {
        if(!str_nit.equals(" ") & !str_empleador.equals(" ")){
            str_empleador = " AND "+str_empleador;
        }
//        if ((!str_cedula.equals(" ") | !str_empleador.equals(" ") | !str_municipio.equals(" "))& !str_obra.equals(" ")) {
//            str_obra = " AND "+str_obra;
//        }
        if ((!str_nit.equals(" ") | !str_empleador.equals(" "))& !str_arl.equals(" ")) {
            str_arl = " AND "+str_arl;
        }
        if ((!str_nit.equals(" ") | !str_empleador.equals(" ") | !str_arl.equals(" "))& !str_ccf.equals(" ")) {
            str_ccf = " AND "+str_ccf;
        }
        if ((!str_nit.equals(" ") | !str_empleador.equals(" ") | !str_arl.equals(" ") | !str_ccf.equals(" "))& !str_actividad.equals(" ")) {
            str_actividad = " AND "+str_actividad;
        }
        if (!str_nit.equals(" ") | !str_empleador.equals(" ") |!str_arl.equals(" ") | !str_ccf.equals(" ") ) {
            str_query = str_query + " WHERE " + str_nit + str_empleador + str_arl + str_ccf + str_actividad;
        }else{
            str_query = str_query + " ORDER BY ID_EMPRESA ASC";
        }
        
        
    
return str_query;
}
}
