/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cambiar_contraseña.java
 *
 * Created on 09-feb-2015, 11:51:08
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.Conexion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.jm.Edicof.Encriptar.Encriptar;
import java.awt.Toolkit;

/**
 *
 * @author Johnnatan
 */
public class Cambiar_contraseña extends javax.swing.JDialog {

    /** Creates new form Cambiar_contraseña */
    public Cambiar_contraseña(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setIconImage(parent.getIconImage());
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        cargar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nombres_Emp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Apellidos_emp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Rol_emp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Con_nueva = new javax.swing.JPasswordField();
        Ver_cont = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cont_actual = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambiar contraseña");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        jLabel1.setText("Nombres");

        Nombres_Emp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombres_Emp.setEnabled(false);

        jLabel2.setText("Apellidos");

        Apellidos_emp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Apellidos_emp.setEnabled(false);

        jLabel3.setText("Rol");

        Rol_emp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Rol_emp.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Apellidos_emp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombres_Emp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rol_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombres_Emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Apellidos_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Rol_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cambiar Contrasena"));

        jLabel4.setText("Contraseña actual");

        Con_nueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Con_nueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Con_nuevaKeyTyped(evt);
            }
        });

        Ver_cont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ver_cont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ver_contKeyTyped(evt);
            }
        });

        jLabel5.setText("Nueva Contraseña");

        jLabel6.setText("Verificar Contraseña");

        Cont_actual.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cont_actual)
                    .addComponent(Con_nueva)
                    .addComponent(Ver_cont, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Cont_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Con_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ver_cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accept_1.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_1.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void Con_nuevaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Con_nuevaKeyTyped
    char a=evt.getKeyChar();
    if(new String(Con_nueva.getPassword()).length()>14) {
        evt.consume();
    }
}//GEN-LAST:event_Con_nuevaKeyTyped

private void Ver_contKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ver_contKeyTyped
    char a=evt.getKeyChar();
    if(new String(Ver_cont.getPassword()).length()>14) {
        evt.consume();
    }
}//GEN-LAST:event_Ver_contKeyTyped

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String cont_nueva;
    String ver_cont;
    String p = null;
    if(!Cont_actual.getPassword().equals("")){
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try{
            r = con.s.executeQuery ("SELECT * FROM t_usuarios WHERE ID_USUARIO="+Main.id_usuario);
            if(r.next()){
                //p=Encriptar.Desencriptar(r.getString("CONT_USUARIO"));
                p=r.getString("CONT_USUARIO");
            }
            con.cerrar();
        }catch(Exception j){
            con.cerrar();
            JOptionPane.showMessageDialog(null,j, "Error",JOptionPane.ERROR_MESSAGE);
        }
        //if(p.equals(new String(Cont_actual.getPassword()))){
        if(p.equals(Encriptar.getMD5(new String(Cont_actual.getPassword())))){
            if(!new String(Con_nueva.getPassword()).equals("") && !new String(Ver_cont.getPassword()).equals("")){
                    cont_nueva = new String(Con_nueva.getPassword());
                    ver_cont = new String(Ver_cont.getPassword());
                    if(ver_cont.equals(cont_nueva)){
                        con.conexion();
                        try{
                            //con.s.executeUpdate("UPDATE T_USUARIOS SET CONT_USUARIO='"+Encriptar.Encriptar(ver_cont)+"' WHERE ID_USUARIO="+Main.id_usuario);
                            con.s.executeUpdate("UPDATE T_USUARIOS SET CONT_USUARIO='"+Encriptar.getMD5(ver_cont)+"' WHERE ID_USUARIO="+Main.id_usuario);
                            con.cerrar();
                        }catch(Exception j){
                            con.cerrar();
                            JOptionPane.showMessageDialog(null,j, "Error",JOptionPane.ERROR_MESSAGE);
                        }
                        JOptionPane.showMessageDialog(null,"La contraseña ha sido cambiada","Confirmacion",JOptionPane.INFORMATION_MESSAGE);
                        Nombres_Emp.setText("");
                        Apellidos_emp.setText("");
                        Rol_emp.setText("");
                        Cont_actual.setText("");
                        Con_nueva.setText("");
                        Ver_cont.setText("");
                        this.dispose();
                    
                    }else{
                        JOptionPane.showMessageDialog(null,"Las contrasenas no coinciden","Error!",JOptionPane.ERROR_MESSAGE);
                    }

            }else{
                JOptionPane.showMessageDialog(null,"Por Favor complete todos los campos","Error!",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"La clave actual es incorrecta","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }else{
        JOptionPane.showMessageDialog(null,"Por Favor ingrese la contraseña actual","Error!",JOptionPane.ERROR_MESSAGE);
    }
            
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Cambiar_contraseña dialog = new Cambiar_contraseña(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidos_emp;
    private javax.swing.JPasswordField Con_nueva;
    private javax.swing.JPasswordField Cont_actual;
    private javax.swing.JTextField Nombres_Emp;
    private javax.swing.JTextField Rol_emp;
    private javax.swing.JPasswordField Ver_cont;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    public void cargar(){
        String cont_act = null;
        String cargo = null;
        String login;
        String s_ap = null;
        String p_ap = null;
        String s_nom = null;
        String p_nom = null;
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try{
            r = con.s.executeQuery ("SELECT * FROM t_usuarios u, t_roles r where ID_USUARIO="+Main.id_usuario+" and u.ID_rol =r.ID_rol");
            if(r.next()){
                if (r.getString("NOMBRE_USUARIO")!=null) {
                    p_nom = r.getString("NOMBRE_USUARIO").toUpperCase();
                }else{
                    p_nom = "";
                }
                if (r.getString("NOMBRE_2_USUARIO")!=null) {
                    s_nom = r.getString("NOMBRE_2_USUARIO").toUpperCase();
                }else{
                    s_nom = "";
                }
                if (r.getString("APELLIDO_USUARIO")!=null) {
                    p_ap = r.getString("APELLIDO_USUARIO").toUpperCase();
                }else{
                    p_ap = "";
                }
                if (r.getString("APELLIDO_2_USUARIO")!=null) {
                    s_ap = r.getString("APELLIDO_2_USUARIO").toUpperCase();
                }else{
                    s_ap = "";
                }
                Nombres_Emp.setText(p_nom+" "+s_nom);
                Apellidos_emp.setText(p_ap+" "+s_ap);
                Rol_emp.setText(r.getString("NOMBRE_ROL"));
                //con.cerrar();
            }
            con.cerrar();
        }catch(Exception j){
            con.cerrar();
            j.printStackTrace();
            JOptionPane.showMessageDialog(null,j,"Error!",JOptionPane.ERROR_MESSAGE);
        }
    }
}
