/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.AutoCompletion;
import com.jm.Edicof.Clases.Conexion;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Johnnatan
 */
public class Casos_pqr extends javax.swing.JDialog {
    TextAutoCompleter tac_empleador = null;
    TextAutoCompleter tac_usuario = null;
    DefaultTableModel modelo;
    Object [] fila = new Object[7];
    static Dimension screenSize = null;

    /**
     * Creates new form Casos_pqr
     */
    public Casos_pqr(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = (DefaultTableModel)casos.getModel();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        Toolkit t = Toolkit.getDefaultToolkit();
        screenSize = Main.getsize();
        //System.out.println(screenSize.height+"x"+screenSize.width);
        this.setSize(screenSize.width, screenSize.height-10);
        this.setLocationRelativeTo(null);
        init();
        ac_radicado();
        ac_empleador();
        ac_nit();
        ac_usuario();
        ac_tipo();
        ac_estado();
        ac_cedula();
        tac_empleador.setMode(0);
        tac_usuario.setMode(0);
        DefaultTableCellRenderer tcr = new FormatRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        casos.getColumnModel().getColumn(0).setCellRenderer(tcr);
        casos.getColumnModel().getColumn(1).setCellRenderer(tcr);
        casos.getColumnModel().getColumn(2).setCellRenderer(tcr);
        casos.getColumnModel().getColumn(3).setCellRenderer(tcr);
        casos.getColumnModel().getColumn(4).setCellRenderer(tcr);
        casos.getColumnModel().getColumn(5).setCellRenderer(tcr);
        casos.getColumnModel().getColumn(6).setCellRenderer(tcr);
    }
    public class FormatRenderer extends DefaultTableCellRenderer{
        public FormatRenderer(){
        }
        @Override
        public void setValue(Object value)
	{
            try{
                if (value != null ){
                    if (value.equals("TEST")) {
                        value = "NO ASIGNADO";
                    }
                    if (value instanceof Timestamp) {
                        value = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(((Timestamp) value).getTime()));
                    }
                }
            }catch(IllegalArgumentException e) {
                e.printStackTrace();
            }
            super.setValue(value);
	}
    }
    public void init(){
        tac_empleador = new TextAutoCompleter(t_empleador);
        tac_usuario = new TextAutoCompleter(t_usuario);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        ver_caso = new javax.swing.JMenuItem();
        asig_usu = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_nit = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        t_empleador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        t_usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_estado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        f_inicio = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        f_final = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cb_radicado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cb_empleado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        casos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        ver_caso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        ver_caso.setText("Ver caso");
        ver_caso.setToolTipText("Esta opcion permite observar toda la informacion y evolucion del caso");
        ver_caso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_casoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ver_caso);

        asig_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_go_1.png"))); // NOI18N
        asig_usu.setText("Asignar Usuario");
        asig_usu.setToolTipText("Esta opcion permite asignar un usuario responsable de solucionar el caso");
        asig_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asig_usuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(asig_usu);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Casos PQR");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterio de busqueda"));

        jLabel1.setText("Nit");

        cb_nit.setEditable(true);
        AutoCompletion.enable(cb_nit);

        jLabel2.setText("Empleador");

        t_empleador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Tipo");

        jLabel4.setText("Usuario asignado");

        t_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Estado");

        jLabel6.setText("Fecha");

        jLabel7.setText("a");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table_tab_search.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filter_delete.png"))); // NOI18N
        jButton2.setText("limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Radicado");

        cb_radicado.setEditable(true);
        AutoCompletion.enable(cb_radicado);

        jLabel9.setText("Empleado");

        cb_empleado.setEditable(true);
        AutoCompletion.enable(cb_empleado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_radicado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_nit, 0, 145, Short.MAX_VALUE)
                                .addComponent(cb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(t_empleador))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(t_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(f_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(f_final, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_empleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cb_radicado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cb_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(t_empleador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(t_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(f_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(f_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(cb_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de la busqueda"));

        casos.setAutoCreateRowSorter(true);
        casos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Radicado", "Tipo", "NIT", "Empresa", "Estado", "Radicado por", "Usuario asignado", "Fecha radicacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        casos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(casos);
        if (casos.getColumnModel().getColumnCount() > 0) {
            casos.getColumnModel().getColumn(0).setResizable(false);
            casos.getColumnModel().getColumn(1).setResizable(false);
            casos.getColumnModel().getColumn(2).setResizable(false);
            casos.getColumnModel().getColumn(3).setResizable(false);
            casos.getColumnModel().getColumn(3).setPreferredWidth(250);
            casos.getColumnModel().getColumn(4).setResizable(false);
            casos.getColumnModel().getColumn(5).setResizable(false);
            casos.getColumnModel().getColumn(6).setResizable(false);
            casos.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_1.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clear_casos();
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try {
            //System.out.println(query(cb_radicado, t_empleador, cb_nit, t_usuario, cb_tipo, cb_estado, f_inicio, f_final, cb_empleado));
            r = con.s.executeQuery (query(cb_radicado, t_empleador, cb_nit, t_usuario, cb_tipo, cb_estado, f_inicio, f_final, cb_empleado));
            while (r.next()) { 
                modelo.addRow(fila);
                modelo.setValueAt(Long.parseLong(r.getString("ID_CASO")),casos.getRowCount()-1,0);
                modelo.setValueAt(r.getString("NOMBRE_TIPO"),casos.getRowCount()-1,1);
                modelo.setValueAt(r.getString("t_empresas.ID_EMPRESA"),casos.getRowCount()-1,2);
                modelo.setValueAt(r.getString("NOMBRE_EMPRESA"),casos.getRowCount()-1,3);
                modelo.setValueAt(r.getString("NOMBRE_ESTADO"),casos.getRowCount()-1,4);
                modelo.setValueAt(r.getString("C1.USUARIO_USUARIO"),casos.getRowCount()-1,5);
                modelo.setValueAt(r.getString("C2.USUARIO_USUARIO"),casos.getRowCount()-1,6);
                modelo.setValueAt(r.getTimestamp("FECHA_CASO"),casos.getRowCount()-1,7);
            }
            con.cerrar();
        }catch (SQLException e) {
            con.cerrar();
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,e,"Error",JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clear_casos();
        cb_radicado.setSelectedItem("Seleccione..");
        cb_nit.setSelectedItem("Seleccione..");
        cb_tipo.setSelectedItem("Seleccione..");
        cb_estado.setSelectedItem("Seleccione..");
        t_empleador.setText("");
        t_usuario.setText("");
        f_inicio.setDate(null);
        f_final.setDate(null);
        cb_empleado.setSelectedItem("Seleccione..");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void asig_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asig_usuActionPerformed
        // TODO add your handling code here:
        if (casos.getSelectedRow()!=-1) {
            //System.out.println(load_usu_creator(casos.getValueAt(casos.getSelectedRow(), 0).toString()));
            if (Main.rol.getText().equals("ADMINISTRADOR") | Main.rol.getText().equals("MASTER") | casos.getValueAt(casos.getSelectedRow(), 5).toString().equals(Main.login.getText())) {
                //System.out.println(casos.getValueAt(casos.getSelectedRow(), 6));
                if (casos.getValueAt(casos.getSelectedRow(), 6).toString().equals("TEST")) {
                    Asig_User_PQR asig =new Asig_User_PQR(this,true,new Long(casos.getValueAt(casos.getSelectedRow(), 0).toString()));
                    asig.setLocationRelativeTo(this);
                    asig.setVisible(true);
                    clear_casos();
                }else{
                    JOptionPane.showMessageDialog(null,"El caso que acaba de seleccionar ya tiene asignado un usuario.","Error",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"No tiene permisos para esta opcion.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"No se ha seleccionado ningun registro de la tabla.","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_asig_usuActionPerformed

    private void ver_casoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_casoActionPerformed
        // TODO add your handling code here:
        if (casos.getSelectedRow()!=-1) {
            View_PQR v =new View_PQR(this,false,new Long(casos.getValueAt(casos.getSelectedRow(), 0).toString()));
            v.setLocationRelativeTo(this);
            v.setVisible(true);
            clear_casos();
        }else{
            JOptionPane.showMessageDialog(null,"No se ha seleccionado ningun registro de la tabla.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ver_casoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Casos_pqr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Casos_pqr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Casos_pqr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casos_pqr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Casos_pqr dialog = new Casos_pqr(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem asig_usu;
    private javax.swing.JTable casos;
    private javax.swing.JComboBox<String> cb_empleado;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JComboBox<String> cb_nit;
    private javax.swing.JComboBox<String> cb_radicado;
    private javax.swing.JComboBox<String> cb_tipo;
    private com.toedter.calendar.JDateChooser f_final;
    private com.toedter.calendar.JDateChooser f_inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_empleador;
    private javax.swing.JTextField t_usuario;
    private javax.swing.JMenuItem ver_caso;
    // End of variables declaration//GEN-END:variables
    public void ac_radicado(){
        cb_radicado.removeAllItems();
        cb_radicado.addItem("Seleccione..");
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try{
            r = con.s.executeQuery ("SELECT * FROM t_caso_pqr ORDER BY ID_CASO ASC;");
            while(r.next()){
                String str=r.getString("ID_CASO");
                cb_radicado.addItem(str);
            }
            con.cerrar();
        }catch(SQLException j){
            con.cerrar();
            j.printStackTrace();
            JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    public void ac_empleador(){
    tac_empleador.removeAllItems();
    tac_empleador.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_EMPRESAS ORDER BY NOMBRE_EMPRESA ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_EMPRESA");
            tac_empleador.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
    public void ac_nit(){
    cb_nit.removeAllItems();
    cb_nit.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_EMPRESAS ORDER BY CAST(`ID_EMPRESA` AS INT) ASC;");
        while(r.next()){
            String str=r.getString("ID_EMPRESA");
            cb_nit.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
    public void ac_usuario(){
    tac_usuario.removeAllItems();
    tac_usuario.addItem("NO ASIGNADO");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM t_usuarios ORDER BY USUARIO_USUARIO ASC;");
        while(r.next()){
            String str=r.getString("USUARIO_USUARIO");
            tac_usuario.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
    public void ac_tipo(){
        cb_tipo.removeAllItems();
        cb_tipo.addItem("Seleccione..");
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try{
            r = con.s.executeQuery ("SELECT * FROM t_tipo_caso_pqr ORDER BY NOMBRE_TIPO ASC;");
            while(r.next()){
                String str=r.getString("NOMBRE_TIPO");
                cb_tipo.addItem(str);
            }
            con.cerrar();
        }catch(SQLException j){
            con.cerrar();
            j.printStackTrace();
            JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    public void ac_estado(){
        cb_estado.removeAllItems();
        cb_estado.addItem("Seleccione..");
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try{
            r = con.s.executeQuery ("SELECT * FROM t_estado_caso_pqr ORDER BY NOMBRE_ESTADO ASC;");
            while(r.next()){
                String str=r.getString("NOMBRE_ESTADO");
                cb_estado.addItem(str);
            }
            con.cerrar();
        }catch(SQLException j){
            con.cerrar();
            j.printStackTrace();
            JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    public void clear_casos(){
        //modelo = (DefaultTableModel)casos.getModel(); 
        while(casos.getRowCount()!=0){
            modelo.removeRow(casos.getRowCount()-1);
        }
    }
    public void ac_cedula(){
    cb_empleado.removeAllItems();
    cb_empleado.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_EMPLEADOS ORDER BY ID_EMP ASC;");
        while(r.next()){
            String str=r.getString("ID_EMP");
            cb_empleado.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
    public String query (javax.swing.JComboBox rad, javax.swing.JTextField empleador, javax.swing.JComboBox nit, javax.swing.JTextField usu, javax.swing.JComboBox tipo, javax.swing.JComboBox estado, com.toedter.calendar.JDateChooser f_ini, com.toedter.calendar.JDateChooser f_fin, javax.swing.JComboBox emp){
    String str_rad = "";
    String str_empleador = "";
    String str_nit= "";
    String str_usu= "";
    String str_tipo= "";
    String str_estado= "";
    String str_date= "";
    String str_empleados= "";
    String str_query = "SELECT *\n" +
                        "FROM\n" +
                        "    t_caso_pqr\n" +
                        "    INNER JOIN t_tipo_caso_pqr \n" +
                        "        ON (t_caso_pqr.ID_TIPO_CASO = t_tipo_caso_pqr.ID_TIPO_CASO)\n" +
                        "    INNER JOIN t_empresas \n" +
                        "        ON (t_caso_pqr.ID_EMPRESA = t_empresas.ID_EMPRESA)\n" +
                        "    INNER JOIN t_usuarios AS C1\n" +
                        "        ON (t_caso_pqr.ID_USUARIO = C1.ID_USUARIO)\n" +
                        "    INNER JOIN t_usuarios AS C2\n" +
                        "        ON (t_caso_pqr.ID_USU_ASIG = C2.ID_USUARIO)\n" +
                        "    INNER JOIN t_estado_caso_pqr \n" +
                        "        ON (t_caso_pqr.ID_ESTADO_CASO = t_estado_caso_pqr.ID_ESTADO_CASO)\n" +
                        "    LEFT JOIN t_casos_empleados \n" +
                        "        ON (t_casos_empleados.ID_CASO = t_caso_pqr.ID_CASO)" ;
    if (!rad.getSelectedItem().equals("Seleccione..") ) {
        str_rad = "t_caso_pqr.ID_CASO = "+rad.getSelectedItem();
    }else{
        str_rad = " ";
    }
    if (!empleador.getText().equals("") & !empleador.getText().equals(" ")) {
        str_empleador = "t_empresas.NOMBRE_EMPRESA='"+empleador.getText()+"'";
    }else{
        str_empleador =" ";
    }
    if (!nit.getSelectedItem().equals("Seleccione..")) {
        str_nit = "t_empresas.ID_EMPRESA='"+nit.getSelectedItem()+"'";
    }else{
        str_nit =" ";
    }
    if (!usu.getText().equals("") & !usu.getText().equals(" ")) {
        if (usu.getText().equals("NO ASIGNADO")) {
            str_usu = "C2.USUARIO_USUARIO='TEST'";
        }else{
            str_usu = "C2.USUARIO_USUARIO='"+usu.getText()+"'";
        }
        
    }else{
        str_usu =" ";
    }
    if (!tipo.getSelectedItem().equals("Seleccione..") ) {
        str_tipo = "t_tipo_caso_pqr.NOMBRE_TIPO='"+tipo.getSelectedItem()+"'";
    }else{
        str_tipo =" ";
    }
    if (!estado.getSelectedItem().equals("Seleccione..") ) {
        str_estado = "t_estado_caso_pqr.NOMBRE_ESTADO='"+estado.getSelectedItem()+"'";
    }else{
        str_estado =" ";
    }
    if (!emp.getSelectedItem().equals("Seleccione..") ) {
        str_empleados = "t_casos_empleados.ID_EMPLEADO='"+emp.getSelectedItem()+"'";
    }else{
        str_empleados =" ";
    }
    if (f_ini.getDate()==null & f_fin.getDate()==null) {
        str_date = " ";
    }else{
        if (f_ini.getDate()!=null & f_fin.getDate()==null) {
            JOptionPane.showMessageDialog(this,"Ingrese la fecha final.","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            if (f_ini.getDate()==null & f_fin.getDate()!=null) {
                JOptionPane.showMessageDialog(this,"Ingrese la fecha inicial.","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                if (f_ini.getDate()!=null & f_fin.getDate()!=null) {
                    str_date = " t_caso_pqr.FECHA_CASO BETWEEN '"+new SimpleDateFormat("yyyy-MM-dd").format(f_ini.getDate())+"' AND '"+new SimpleDateFormat("yyyy-MM-dd").format(f_fin.getDate())+"'";
                }
            }
        }
    }
    if(!str_rad.equals(" ") & !str_empleador.equals(" ")){
        str_empleador = " AND "+str_empleador;
    }
    if ((!str_rad.equals(" ") | !str_empleador.equals(" "))& !str_nit.equals(" ")) {
        str_nit = " AND "+str_nit;
    }
    if ((!str_rad.equals(" ") | !str_empleador.equals(" ") | !str_nit.equals(" "))& !str_usu.equals(" ")) {
        str_usu = " AND "+str_usu;
    }
    if ((!str_rad.equals(" ") | !str_empleador.equals(" ") | !str_nit.equals(" ") | !str_usu.equals(" "))& !str_tipo.equals(" ")) {
        str_tipo = " AND "+str_tipo;
    }
    if ((!str_rad.equals(" ") | !str_empleador.equals(" ") | !str_nit.equals(" ") | !str_usu.equals(" ") | !str_tipo.equals(" "))& !str_estado.equals(" ")) {
        str_estado = " AND "+str_estado;
    }
    if ((!str_rad.equals(" ") | !str_empleador.equals(" ") | !str_nit.equals(" ") | !str_usu.equals(" ") | !str_tipo.equals(" ") | !str_estado.equals(" "))& !str_empleados.equals(" ")) {
        str_empleados = " AND "+str_empleados;
    }
    if ((!str_rad.equals(" ") | !str_empleador.equals(" ") | !str_nit.equals(" ") | !str_usu.equals(" ") | !str_tipo.equals(" ") | !str_estado.equals(" ") | !str_empleados.equals(" "))& !str_date.equals(" ")) {
        str_date = " AND "+str_date;
    }
    
    if (!str_rad.equals(" ") | !str_empleador.equals(" ") | !str_nit.equals(" ") | !str_usu.equals(" ") | !str_tipo.equals(" ") | !str_estado.equals(" ") | !str_empleados.equals(" ") | !str_date.equals(" ")) {
        str_query = str_query + " WHERE " + str_rad + str_empleador + str_nit + str_usu + str_tipo + str_estado +str_empleados +str_date+ " \n GROUP BY t_caso_pqr.ID_CASO \n ORDER BY FECHA_CASO DESC";
    }else{
        str_query = str_query + " \n GROUP BY t_caso_pqr.ID_CASO \n ORDER BY FECHA_CASO DESC";
    }
    return str_query;
}
    public String load_usu_creator(String c){
        String ret ="";
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try{
            r = con.s.executeQuery ("SELECT *\n" +
                            "FROM\n" +
                            "    t_caso_pqr\n" +
                            "    INNER JOIN t_tipo_caso_pqr \n" +
                            "        ON (t_caso_pqr.ID_TIPO_CASO = t_tipo_caso_pqr.ID_TIPO_CASO)\n" +
                            "    INNER JOIN t_empresas \n" +
                            "        ON (t_caso_pqr.ID_EMPRESA = t_empresas.ID_EMPRESA)\n" +
                            "    INNER JOIN t_usuarios AS C1\n" +
                            "        ON (t_caso_pqr.ID_USUARIO = C1.ID_USUARIO)\n" +
                            "    INNER JOIN t_usuarios AS C2\n" +
                            "        ON (t_caso_pqr.ID_USU_ASIG = C2.ID_USUARIO)\n" +
                            "    INNER JOIN t_estado_caso_pqr \n" +
                            "        ON (t_caso_pqr.ID_ESTADO_CASO = t_estado_caso_pqr.ID_ESTADO_CASO)\n" +
                            "    LEFT JOIN t_casos_empleados \n" +
                            "        ON (t_casos_empleados.ID_CASO = t_caso_pqr.ID_CASO) WHERE t_caso_pqr.ID_CASO="+c);
            if(r.next()){
                ret = r.getString("C1.USUARIO_USUARIO");
            }
            con.cerrar();
        }catch(SQLException j){
            con.cerrar();
            j.printStackTrace();
            JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
        }
        return ret;
    }



}
