/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.Conexion;
import com.jm.Edicof.Clases.Struct_Cruce_Precalculo;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Johnnatan
 */
public class CruceSeguridadSocial_Menu extends javax.swing.JDialog {
    DefaultTableModel modelo_empresas = null;
    //DefaultTableModel modelo_cruce_prec = null;
    /**
     * Creates new form CrucePrecalculo
     */
    public CruceSeguridadSocial_Menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo_empresas=(DefaultTableModel) empresas.getModel();
        //modelo_cruce_prec=(DefaultTableModel) cruce_seguridad.getModel();
        load_empresas(dia.getValue(),mes.getMonth()+1,año.getYear());
//        DefaultTableCellRenderer tcr = new FormatRenderer();
//        tcr.setHorizontalAlignment(SwingConstants.CENTER);
//        cruce_seguridad.getColumnModel().getColumn(0).setCellRenderer(tcr);
//        cruce_seguridad.getColumnModel().getColumn(1).setCellRenderer(tcr);
//        cruce_seguridad.getColumnModel().getColumn(2).setCellRenderer(tcr);
//        cruce_seguridad.getColumnModel().getColumn(3).setCellRenderer(tcr);
//        cruce_seguridad.getColumnModel().getColumn(4).setCellRenderer(tcr);
//        cruce_seguridad.getColumnModel().getColumn(5).setCellRenderer(tcr);
//        cruce_seguridad.getColumnModel().getColumn(6).setCellRenderer(tcr);
//        cruce_seguridad.getColumnModel().getColumn(7).setCellRenderer(tcr);
//        DefaultTableCellRenderer tcr1 = new DefaultTableCellRenderer();
//        tcr1.setHorizontalAlignment(SwingConstants.CENTER);
//        prec_defs.getColumnModel().getColumn(0).setCellRenderer(tcr1);
//        prec_defs.getColumnModel().getColumn(1).setCellRenderer(tcr1);
//        prec_defs.getColumnModel().getColumn(2).setCellRenderer(tcr1);
//        prec_defs.getColumnModel().getColumn(3).setCellRenderer(tcr1);
//        
//        prec_defs.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
//            @Override
//            public void valueChanged(ListSelectionEvent event) {
//                clear_cruc();
//            }
//        });
//        cruce_seguridad.getModel().addTableModelListener(new TableModelListener() {
//            @Override
//            public void tableChanged(TableModelEvent e) {
//                if (e.getType()==TableModelEvent.INSERT||e.getType()==TableModelEvent.DELETE) {
//                    if (cruce_seguridad.getRowCount()!=0) {
//                        btn_almacenar.setEnabled(true);
//                    }else{
//                        btn_almacenar.setEnabled(false);
//                    }
//                }
//            }
//    });
    }
//    public class FormatRenderer extends DefaultTableCellRenderer{
//        Locale locale = new Locale("es","CO"); // elegimos Argentina
//        NumberFormat nf = NumberFormat.getCurrencyInstance(locale);
//        public FormatRenderer(){
//        
//        }
//        @Override
//        public void setValue(Object value)
//	{
//            try{
//                if (value != null ){
//                    if (value instanceof Float) {
//                        value = nf.format(value);
//                    }
//                }
//            }catch(IllegalArgumentException e) {
//                e.printStackTrace();
//            }
//            super.setValue(value);
//	}
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        add_cruce = new javax.swing.JMenuItem();
        view_cruce = new javax.swing.JMenuItem();
        delete_cruce = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        dia = new com.toedter.components.JSpinField();
        mes = new com.toedter.calendar.JMonthChooser();
        año = new com.toedter.calendar.JYearChooser();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_almacenar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        registros = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        empresas = new javax.swing.JTable();

        add_cruce.setText("jMenuItem5");
        add_cruce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cruceActionPerformed(evt);
            }
        });
        jPopupMenu1.add(add_cruce);

        view_cruce.setText("Consultar");
        jPopupMenu1.add(view_cruce);

        delete_cruce.setText("jMenuItem5");
        delete_cruce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_cruceActionPerformed(evt);
            }
        });
        jPopupMenu1.add(delete_cruce);

        jMenu2.setText("Cruces de Precalculo");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_inspector.png"))); // NOI18N
        jMenuItem2.setText("Consultar Cruce");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jMenuItem3.setText("Eliminar Cruce");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jPopupMenu1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cruce de Seguridad Social - Busqueda");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione fecha limite seguridad"));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table_tab_search.png"))); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        dia.setMinimum(-2147483647);
        dia.setValue(1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_2.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btn_almacenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table_save.png"))); // NOI18N
        btn_almacenar.setText("Almacenar Cruce");
        btn_almacenar.setEnabled(false);
        btn_almacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_almacenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(btn_almacenar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_almacenar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

        jLabel1.setText("Registros");

        registros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registros.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(registros, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado busqueda empresas"));

        empresas.setAutoCreateRowSorter(true);
        empresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIT", "Razon Social", "Fecha Creacion", "Cruce Seguridad Social"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empresas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane3.setViewportView(empresas);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clear_empresas();
        //clear_cruc();
        load_empresas(dia.getValue(),mes.getMonth()+1,año.getYear());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_almacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_almacenarActionPerformed
        // TODO add your handling code here:
        /*int s = JOptionPane.showConfirmDialog(this,"Usted esta a punto de almacenar el cruce de precalculo para\nel siguiente precalculo definitivo:\nID: "+prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 0)+"\nFecha inicial: "+prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 1)+"\nFecha final: "+prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 2)+"\nDesea Continuar?", "Advertencia",JOptionPane.WARNING_MESSAGE);
        if(s==JOptionPane.YES_OPTION){
            if (prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 4).toString().equals("NO")) {
                //this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                Conexion con = new Conexion();
                con.conexion();
                int id_cruce=0;
                boolean conf=true;
                try {
                    ResultSet r;
                    int i = con.s.executeUpdate("INSERT INTO `t_cruce_precalculo`(`F_REGISTRO`, `ID_USUARIO`, `ID_PREC`) VALUES ('"+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date())+"','"+Main.id_usuario+"',"+prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 0)+")", Statement.RETURN_GENERATED_KEYS);
                    if (i==1) {
                        r = con.s.getGeneratedKeys();
                        if (r.next()) {
                            id_cruce=r.getInt(1);
                        }
                    }
                    for (int j = 0; j < cruce_seguridad.getRowCount(); j++) {
                        con.s.executeUpdate("INSERT INTO `t_det_cruce_precalculo`(`ID_EMPRESA`, `FIC_ANT`, `FIC_ACT`, `DIF_FIC`, `TOT_ANT`, `TOT_ACT`, `DIF_TOT`, `ID_CRUCE_PREC`) VALUES ('"+cruce_seguridad.getValueAt(j, 0)+"',"+cruce_seguridad.getValueAt(j, 2)+","+cruce_seguridad.getValueAt(j, 3)+","+cruce_seguridad.getValueAt(j, 4)+","+cruce_seguridad.getValueAt(j, 5)+","+cruce_seguridad.getValueAt(j, 6)+","+cruce_seguridad.getValueAt(j, 7)+","+id_cruce+")");
                        modelo_cruce_prec.removeRow(j);
                        j=j-1;
                        conf=conf&true;
                    }
                    con.cerrar();
                }catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
                    con.cerrar();
                    conf=conf&false;
                }
                if (conf) {
                    JOptionPane.showMessageDialog(this,"El cruce de precalculo ha sido almacenado correctamente","Confirmación",JOptionPane.INFORMATION_MESSAGE);
                }
                clear_empresas();
                //clear_cruc();
                //load_empresas();
            } else {
                JOptionPane.showMessageDialog(this,"Debe seleccionar un precalculo definitivo que no tenga ningun cruce almacenado","Error",JOptionPane.ERROR_MESSAGE);
            }
        }    */
    }//GEN-LAST:event_btn_almacenarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        /*if (prec_defsertert.getRowCount()>0) {
            if (prec_defsertert.getSelectedRow()!=-1) {
                if (prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 4).toString().equals("SI")) {
                    JFileChooser fc_rep_cruce = new JFileChooser();
                    fc_rep_cruce.setFileFilter(new FileNameExtensionFilter("Archivos Excel (*.xlsx)","xlsx"));
                    fc_rep_cruce.setSelectedFile(new File("Reporte_Cruce_Precalculo_del_"+prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 1)+"_al_"+prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 2)));
                    System.out.println("Extencion: "+((FileNameExtensionFilter)fc_rep_cruce.getFileFilter()).getExtensions()[0]);
                    if(fc_rep_cruce.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
                        Struct_Cruce_Precalculo s = new Struct_Cruce_Precalculo(this,fc_rep_cruce.getSelectedFile().getAbsolutePath(),((FileNameExtensionFilter)fc_rep_cruce.getFileFilter()).getExtensions()[0], Integer.parseInt(prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 0).toString()),fc_rep_cruce.getSelectedFile().toString());
                        Wait_rep t = new Wait_rep(this,true,s);
                        t.setLocationRelativeTo(null);
                        t.setVisible(true);
                        this.dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(this,"El registro seleccionado no tiene ningun Cruce generado anteriormente","Error",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this,"Debe seleccionar un registro en la tabla de precalculos definitivos","Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"La tabla de precalculos definitivos debe tener al menos 1 registro","Error",JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        /*if (prec_defsertert.getSelectedRow()!=-1) {
            if (prec_defsertert.getRowCount()==(prec_defsertert.getSelectedRow()+1)) {
                if (prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 4).toString().equals("SI")) {
                    delete_cruce_prec();
                } else {
                    JOptionPane.showMessageDialog(this,"El registro seleccionado no tiene asociado ningún Cruce de Precalculo","Error",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                if (prec_defsertert.getValueAt(prec_defsertert.getSelectedRow()+1, 4).toString().equals("NO")) {
                    delete_cruce_prec();
                } else {
                    JOptionPane.showMessageDialog(this,"No se puede eliminar un Cruce de Precalculo que no sea el ultimo generado","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            if (prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 4).toString().equals("SI")) {
                int s = JOptionPane.showConfirmDialog(this,"Usted esta a punto de eliminar el cruce de precalculo para\nel siguiente precalculo definitivo:\nID: "+prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 0)+"\nFecha inicial: "+prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 1)+"\nFecha final: "+prec_defsertert.getValueAt(prec_defsertert.getSelectedRow(), 2)+"\nDesea Continuar?", "Advertencia",JOptionPane.WARNING_MESSAGE);
                if(s==JOptionPane.YES_OPTION){
                    
                }
                
            }else{
                JOptionPane.showMessageDialog(this,"El registro seleccionado no tiene asociado ningún Cruce de Precalculo","Error",JOptionPane.ERROR_MESSAGE);
            }   
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un registro en la tabla de precalculos definitivos","Error",JOptionPane.ERROR_MESSAGE);
        }    */
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void add_cruceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cruceActionPerformed
        // TODO add your handling code here:
        generate_cruce();
    }//GEN-LAST:event_add_cruceActionPerformed

    private void delete_cruceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_cruceActionPerformed
        // TODO add your handling code here:
        delete_cruce();
    }//GEN-LAST:event_delete_cruceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CruceSeguridadSocial_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CruceSeguridadSocial_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CruceSeguridadSocial_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CruceSeguridadSocial_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CruceSeguridadSocial_Menu dialog = new CruceSeguridadSocial_Menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem add_cruce;
    private com.toedter.calendar.JYearChooser año;
    private javax.swing.JButton btn_almacenar;
    private javax.swing.JMenuItem delete_cruce;
    private com.toedter.components.JSpinField dia;
    private javax.swing.JTable empresas;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JMonthChooser mes;
    private javax.swing.JLabel registros;
    private javax.swing.JMenuItem view_cruce;
    // End of variables declaration//GEN-END:variables
    private void clear_empresas() {
        while(empresas.getRowCount()!=0){
            modelo_empresas.removeRow(empresas.getRowCount()-1);
        }
    }
    private void load_empresas(int dia, int mes, int año) {
        String nit =""; 
        Conexion con = new Conexion();
        Conexion con1 = new Conexion();
        con.conexion();
        con1.conexion();
        try {
            ResultSet r,r1;
            r = con.s.executeQuery ("SELECT * FROM t_empresas WHERE F_LIM_SEG = "+dia);
            while (r.next()) {    
                modelo_empresas.addRow(new Object[4]);
                nit = r.getString("ID_EMPRESA");
                modelo_empresas.setValueAt(nit,empresas.getRowCount()-1,0);
                modelo_empresas.setValueAt(r.getString("NOMBRE_EMPRESA"),empresas.getRowCount()-1,1);
                r1 = con1.s.executeQuery ("SELECT * FROM `t_cruce_seguridad_social` WHERE ID_EMPRESA = "+nit+" AND MES_SEG = "+mes+" AND AÑO_SEG = "+año);
                if (r1.next()) {
                    modelo_empresas.setValueAt(r.getString("F_REGISTRO"),empresas.getRowCount()-1,2);
                    modelo_empresas.setValueAt("SI",empresas.getRowCount()-1,3);
                }else{
                    modelo_empresas.setValueAt("--",empresas.getRowCount()-1,2);
                    modelo_empresas.setValueAt("NO",empresas.getRowCount()-1,3);
                }
            }
            con.cerrar();
            con1.cerrar();
        }catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
            con.cerrar();
            con1.cerrar();
        }
    }
    private void generate_cruce(){
        if (empresas.getSelectedRow()!=-1) {
            if (empresas.getValueAt(empresas.getSelectedRow(), 3).equals("NO")) {
                CruceSeguridadSocial_Add add = new CruceSeguridadSocial_Add(this, true);
                add.setLocationRelativeTo(this);
                add.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this,"La empresa seleccionada ya tiene asociado un Cruce de Seguridad Social","Error",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,"Debe seleccionar una empresa para generar el cruce","Error",JOptionPane.ERROR_MESSAGE);
        }
            
    }
    private void delete_cruce(){
        if (empresas.getSelectedRow()!=-1) {
            int s = JOptionPane.showConfirmDialog(this,"Usted esta a punto de eliminar el Cruce de Seguridad Social:\nID: "+empresas.getValueAt(empresas.getSelectedRow(), 0)+"\nRazón social: "+empresas.getValueAt(empresas.getSelectedRow(), 1)+"\nFecha creación: "+empresas.getValueAt(empresas.getSelectedRow(), 2)+"\nDesea Continuar?", "Advertencia",JOptionPane.WARNING_MESSAGE);
            if(s==JOptionPane.YES_OPTION){
                Conexion con = new Conexion();
                con.conexion();
                try {
                    con.s.executeUpdate("DELETE FROM `t_cruce_seguridad_social` WHERE ID_CRUCE_SEG= "+empresas.getValueAt(empresas.getSelectedRow(), 0));
                    con.cerrar();
                }catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
                    con.cerrar();
                }
                JOptionPane.showMessageDialog(this,"El Precalculo Definitivo fue eliminado satisfactoriamente","Confirmación",JOptionPane.INFORMATION_MESSAGE);
                clear_empresas();
                load_empresas(dia.getValue(),mes.getMonth()+1,año.getYear());
            }
        } else {
            JOptionPane.showMessageDialog(this,"Debe seleccionar una empresa para generar el cruce","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
}
