/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.Conexion;
import com.jm.Edicof.Clases.Struct_Cruce_Precalculo;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Johnnatan
 */
public class CrucePrecalculo extends javax.swing.JDialog {
    DefaultTableModel modelo_prec_def = null;
    DefaultTableModel modelo_cruce_prec = null;
    /**
     * Creates new form CrucePrecalculo
     */
    public CrucePrecalculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo_prec_def=(DefaultTableModel) prec_defs.getModel();
        modelo_cruce_prec=(DefaultTableModel) cruce_prec.getModel();
        load_prec();
        DefaultTableCellRenderer tcr = new FormatRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        cruce_prec.getColumnModel().getColumn(0).setCellRenderer(tcr);
        cruce_prec.getColumnModel().getColumn(1).setCellRenderer(tcr);
        cruce_prec.getColumnModel().getColumn(2).setCellRenderer(tcr);
        cruce_prec.getColumnModel().getColumn(3).setCellRenderer(tcr);
        cruce_prec.getColumnModel().getColumn(4).setCellRenderer(tcr);
        cruce_prec.getColumnModel().getColumn(5).setCellRenderer(tcr);
        cruce_prec.getColumnModel().getColumn(6).setCellRenderer(tcr);
        cruce_prec.getColumnModel().getColumn(7).setCellRenderer(tcr);
        DefaultTableCellRenderer tcr1 = new DefaultTableCellRenderer();
        tcr1.setHorizontalAlignment(SwingConstants.CENTER);
        prec_defs.getColumnModel().getColumn(0).setCellRenderer(tcr1);
        prec_defs.getColumnModel().getColumn(1).setCellRenderer(tcr1);
        prec_defs.getColumnModel().getColumn(2).setCellRenderer(tcr1);
        prec_defs.getColumnModel().getColumn(3).setCellRenderer(tcr1);
        
        prec_defs.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent event) {
                clear_cruc();
            }
        });
        cruce_prec.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType()==TableModelEvent.INSERT||e.getType()==TableModelEvent.DELETE) {
                    if (cruce_prec.getRowCount()!=0) {
                        btn_almacenar.setEnabled(true);
                    }else{
                        btn_almacenar.setEnabled(false);
                    }
                }
            }
    });
    }
    public class FormatRenderer extends DefaultTableCellRenderer{
        Locale locale = new Locale("es","CO"); // elegimos Argentina
        NumberFormat nf = NumberFormat.getCurrencyInstance(locale);
        public FormatRenderer(){
        
        }
        @Override
        public void setValue(Object value)
	{
            try{
                if (value != null ){
                    if (value instanceof Float) {
                        value = nf.format(value);
                    }
                }
            }catch(IllegalArgumentException e) {
                e.printStackTrace();
            }
            super.setValue(value);
	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        año = new com.toedter.calendar.JYearChooser();
        mes = new com.toedter.calendar.JMonthChooser();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prec_defs = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cruce_prec = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btn_almacenar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        registros = new javax.swing.JLabel();

        jMenu1.setText("Precalculos");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jMenuItem4.setText("Eliminar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jPopupMenu1.add(jMenu1);

        jMenu2.setText("Cruces de Precalculo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross_promotion_selling.png"))); // NOI18N
        jMenuItem1.setText("Generar Cruce");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_inspector.png"))); // NOI18N
        jMenuItem2.setText("Consultar Cruce");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jMenuItem3.setText("Eliminar Cruce");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jPopupMenu1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cruce de Precalculos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione mes y año"));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table_tab_search.png"))); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Precalculos definitivos"));

        prec_defs.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        prec_defs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha Inicial", "Fecha Final", "Fecha Creación", "Cruce Precalculo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prec_defs.setComponentPopupMenu(jPopupMenu1);
        prec_defs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prec_defsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prec_defs);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion del Cruce"));

        cruce_prec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIT", "Nombre Empresa", "FIC Anterior", "FIC Actual", "Diferencia FIC", "Total Anterior", "Total Actual", "Diferencia Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(cruce_prec);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_2.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione mes y año"));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross_promotion_selling.png"))); // NOI18N
        jButton3.setText("Generar Cruce");
        jButton3.setToolTipText("Seleccione una fila en la tabla de precalculos definitivos para generar el cruce");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_almacenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table_save.png"))); // NOI18N
        btn_almacenar.setText("Almacenar Cruce");
        btn_almacenar.setEnabled(false);
        btn_almacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_almacenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_almacenar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btn_almacenar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

        jLabel1.setText("Registros");

        registros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registros.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registros, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(registros, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clear_prec();
        clear_cruc();
        load_prec();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        calcular_cruce();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void prec_defsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prec_defsMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            //calcular_cruce();
        }
    }//GEN-LAST:event_prec_defsMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        calcular_cruce();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_almacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_almacenarActionPerformed
        // TODO add your handling code here:
        int s = JOptionPane.showConfirmDialog(this,"Usted esta a punto de almacenar el cruce de precalculo para\nel siguiente precalculo definitivo:\nID: "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 0)+"\nFecha inicial: "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 1)+"\nFecha final: "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 2)+"\nDesea Continuar?", "Advertencia",JOptionPane.WARNING_MESSAGE);
        if(s==JOptionPane.YES_OPTION){
            if (prec_defs.getValueAt(prec_defs.getSelectedRow(), 4).toString().equals("NO")) {
                //this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                Conexion con = new Conexion();
                con.conexion();
                int id_cruce=0;
                boolean conf=true;
                try {
                    ResultSet r;
                    int i = con.s.executeUpdate("INSERT INTO `t_cruce_precalculo`(`F_REGISTRO`, `ID_USUARIO`, `ID_PREC`) VALUES ('"+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date())+"','"+Main.id_usuario+"',"+prec_defs.getValueAt(prec_defs.getSelectedRow(), 0)+")", Statement.RETURN_GENERATED_KEYS);
                    if (i==1) {
                        r = con.s.getGeneratedKeys();
                        if (r.next()) {
                            id_cruce=r.getInt(1);
                        }
                    }
                    for (int j = 0; j < cruce_prec.getRowCount(); j++) {
                        con.s.executeUpdate("INSERT INTO `t_det_cruce_precalculo`(`ID_EMPRESA`, `FIC_ANT`, `FIC_ACT`, `DIF_FIC`, `TOT_ANT`, `TOT_ACT`, `DIF_TOT`, `ID_CRUCE_PREC`) VALUES ('"+cruce_prec.getValueAt(j, 0)+"',"+cruce_prec.getValueAt(j, 2)+","+cruce_prec.getValueAt(j, 3)+","+cruce_prec.getValueAt(j, 4)+","+cruce_prec.getValueAt(j, 5)+","+cruce_prec.getValueAt(j, 6)+","+cruce_prec.getValueAt(j, 7)+","+id_cruce+")");
                        modelo_cruce_prec.removeRow(j);
                        j=j-1;
                        conf=conf&true;
                    }
                    con.cerrar();
                }catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
                    con.cerrar();
                    conf=conf&false;
                }
                if (conf) {
                    JOptionPane.showMessageDialog(this,"El cruce de precalculo ha sido almacenado correctamente","Confirmación",JOptionPane.INFORMATION_MESSAGE);
                }
                clear_prec();
                clear_cruc();
                load_prec();
            } else {
                JOptionPane.showMessageDialog(this,"Debe seleccionar un precalculo definitivo que no tenga ningun cruce almacenado","Error",JOptionPane.ERROR_MESSAGE);
            }
        }    
    }//GEN-LAST:event_btn_almacenarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (prec_defs.getRowCount()>0) {
            if (prec_defs.getSelectedRow()!=-1) {
                if (prec_defs.getValueAt(prec_defs.getSelectedRow(), 4).toString().equals("SI")) {
                    JFileChooser fc_rep_cruce = new JFileChooser();
                    fc_rep_cruce.setFileFilter(new FileNameExtensionFilter("Archivos Excel (*.xlsx)","xlsx"));
                    fc_rep_cruce.setSelectedFile(new File("Reporte_Cruce_Precalculo_del_"+prec_defs.getValueAt(prec_defs.getSelectedRow(), 1)+"_al_"+prec_defs.getValueAt(prec_defs.getSelectedRow(), 2)));
                    System.out.println("Extencion: "+((FileNameExtensionFilter)fc_rep_cruce.getFileFilter()).getExtensions()[0]);
                    if(fc_rep_cruce.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
                        Struct_Cruce_Precalculo s = new Struct_Cruce_Precalculo(this,fc_rep_cruce.getSelectedFile().getAbsolutePath(),((FileNameExtensionFilter)fc_rep_cruce.getFileFilter()).getExtensions()[0], Integer.parseInt(prec_defs.getValueAt(prec_defs.getSelectedRow(), 0).toString()),fc_rep_cruce.getSelectedFile().toString());
                        Wait_rep t = new Wait_rep(this,true,s);
                        t.setLocationRelativeTo(null);
                        t.setVisible(true);
                        this.dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(this,"El registro seleccionado no tiene ningun Cruce generado anteriormente","Error",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this,"Debe seleccionar un registro en la tabla de precalculos definitivos","Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"La tabla de precalculos definitivos debe tener al menos 1 registro","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (prec_defs.getSelectedRow()!=-1) {
            if (prec_defs.getRowCount()==(prec_defs.getSelectedRow()+1)) {
                if (prec_defs.getValueAt(prec_defs.getSelectedRow(), 4).toString().equals("SI")) {
                    delete_cruce_prec();
                } else {
                    JOptionPane.showMessageDialog(this,"El registro seleccionado no tiene asociado ningún Cruce de Precalculo","Error",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                if (prec_defs.getValueAt(prec_defs.getSelectedRow()+1, 4).toString().equals("NO")) {
                    delete_cruce_prec();
                } else {
                    JOptionPane.showMessageDialog(this,"No se puede eliminar un Cruce de Precalculo que no sea el ultimo generado","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            if (prec_defs.getValueAt(prec_defs.getSelectedRow(), 4).toString().equals("SI")) {
                int s = JOptionPane.showConfirmDialog(this,"Usted esta a punto de eliminar el cruce de precalculo para\nel siguiente precalculo definitivo:\nID: "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 0)+"\nFecha inicial: "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 1)+"\nFecha final: "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 2)+"\nDesea Continuar?", "Advertencia",JOptionPane.WARNING_MESSAGE);
                if(s==JOptionPane.YES_OPTION){
                    
                }
                
            }else{
                JOptionPane.showMessageDialog(this,"El registro seleccionado no tiene asociado ningún Cruce de Precalculo","Error",JOptionPane.ERROR_MESSAGE);
            }   
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un registro en la tabla de precalculos definitivos","Error",JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if (prec_defs.getSelectedRow()!=-1) {
            int s = JOptionPane.showConfirmDialog(this,"Usted esta a punto de eliminar el Precalculo Definitivo:\nID: "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 0)+"\nFecha inicial: "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 1)+"\nFecha final: "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 2)+"\nDesea Continuar?", "Advertencia",JOptionPane.WARNING_MESSAGE);
            if(s==JOptionPane.YES_OPTION){
                Conexion con = new Conexion();
                con.conexion();
                try {
                    con.s.executeUpdate("DELETE FROM `t_precalculo_definitivo` WHERE ID_PREC= "+prec_defs.getValueAt(prec_defs.getSelectedRow(),0));
                    con.cerrar();
                }catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
                    con.cerrar();
                }
                JOptionPane.showMessageDialog(this,"El Precalculo Definitivo fue eliminado satisfactoriamente","Confirmación",JOptionPane.INFORMATION_MESSAGE);
                clear_prec();
                clear_cruc();
                load_prec();
            }

        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un registro en la tabla de precalculos definitivos","Error",JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrucePrecalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrucePrecalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrucePrecalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrucePrecalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrucePrecalculo dialog = new CrucePrecalculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser año;
    private javax.swing.JButton btn_almacenar;
    private javax.swing.JTable cruce_prec;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JMonthChooser mes;
    private javax.swing.JTable prec_defs;
    private javax.swing.JLabel registros;
    // End of variables declaration//GEN-END:variables
    private void delete_cruce_prec(){
        Conexion con = new Conexion();
        con.conexion();
        try {
            con.s.executeUpdate("DELETE FROM `t_cruce_precalculo` WHERE ID_PREC= "+prec_defs.getValueAt(prec_defs.getSelectedRow(),0));
            con.cerrar();
        }catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
            con.cerrar();
        }
        JOptionPane.showMessageDialog(this,"El Cruce de Precalculo fue eliminado satisfactoriamente","Confirmación",JOptionPane.INFORMATION_MESSAGE);
        clear_prec();
        clear_cruc();
        load_prec();
    }
    private void clear_prec() {
        while(prec_defs.getRowCount()!=0){
            modelo_prec_def.removeRow(prec_defs.getRowCount()-1);
        }
    }
    private void clear_cruc(){
        while(cruce_prec.getRowCount()!=0){
            modelo_cruce_prec.removeRow(cruce_prec.getRowCount()-1);
        }
        registros.setText(String.valueOf(cruce_prec.getRowCount()));
    }
    private void load_prec() {
        Calendar fecha_1 = Calendar.getInstance();
        Calendar fecha_2 = Calendar.getInstance();
        fecha_1.set(año.getYear(), mes.getMonth(),1);
        fecha_2.set(año.getYear(), mes.getMonth(),1);
        fecha_1.set(Calendar.DATE, fecha_1.getActualMinimum(Calendar.DATE));
        fecha_2.set(Calendar.DATE, fecha_1.getActualMaximum(Calendar.DATE));
        Conexion con = new Conexion();
        Conexion con1 = new Conexion();
        con.conexion();
        con1.conexion();
        try {
            ResultSet r,r1;
            r = con.s.executeQuery ("SELECT * FROM t_precalculo_definitivo WHERE (F_INICIAL BETWEEN '"+new SimpleDateFormat("yyyy-MM-dd").format(fecha_1.getTime())+"' AND '"+new SimpleDateFormat("yyyy-MM-dd").format(fecha_2.getTime())+"') AND (F_FINAL BETWEEN '"+new SimpleDateFormat("yyyy-MM-dd").format(fecha_1.getTime())+"' AND '"+new SimpleDateFormat("yyyy-MM-dd").format(fecha_2.getTime())+"') ORDER BY F_INICIAL,F_FINAL ASC");
            while (r.next()) {    
                modelo_prec_def.addRow(new Object[4]);
                modelo_prec_def.setValueAt(r.getString("ID_PREC"),prec_defs.getRowCount()-1,0);
                modelo_prec_def.setValueAt(r.getString("F_INICIAL"),prec_defs.getRowCount()-1,1);
                modelo_prec_def.setValueAt(r.getString("F_FINAL"),prec_defs.getRowCount()-1,2);
                modelo_prec_def.setValueAt(r.getString("F_REGISTRO"),prec_defs.getRowCount()-1,3);
                r1 = con1.s.executeQuery ("SELECT * FROM `t_cruce_precalculo` WHERE ID_PREC ="+prec_defs.getValueAt(prec_defs.getRowCount()-1,0));
                if (r1.next()) {
                    modelo_prec_def.setValueAt("SI",prec_defs.getRowCount()-1,4);
                }else{
                    modelo_prec_def.setValueAt("NO",prec_defs.getRowCount()-1,4);
                }
            }
            con.cerrar();
            con1.cerrar();
        }catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
            con.cerrar();
            con1.cerrar();
        }
    }
    private void calcular_cruce(){
        float fic_1=0,fic_2=0, total_1=0, total_2=0;
        if (prec_defs.getSelectedRow()!=-1) {
            if (prec_defs.getValueAt(prec_defs.getSelectedRow(), 4).toString().equals("NO")) {
                if (prec_defs.getSelectedRow()==0) {
                    while(cruce_prec.getRowCount()!=0){
                        modelo_cruce_prec.removeRow(cruce_prec.getRowCount()-1);
                    }
                    Conexion con = new Conexion();
                    con.conexion();
                    try {
                        ResultSet r;
                        r = con.s.executeQuery ("SELECT * "
                                + "FROM t_det_precalculos INNER JOIN t_empresas ON (t_det_precalculos.ID_EMPRESA = t_empresas.ID_EMPRESA) "
                                + "WHERE ID_PREC = "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 0)+" "
                                + "ORDER BY t_det_precalculos.ID_EMPRESA ASC");
                        while (r.next()) {
                            modelo_cruce_prec.addRow(new Object[8]);
                            modelo_cruce_prec.setValueAt(r.getString("ID_EMPRESA"),cruce_prec.getRowCount()-1,0);
                            modelo_cruce_prec.setValueAt(r.getString("NOMBRE_EMPRESA"),cruce_prec.getRowCount()-1,1);
                            modelo_cruce_prec.setValueAt(new Float("0"),cruce_prec.getRowCount()-1,2);
                            fic_2=r.getFloat("FIC");
                            modelo_cruce_prec.setValueAt(fic_2,cruce_prec.getRowCount()-1,3);
                            modelo_cruce_prec.setValueAt(fic_2-fic_1,cruce_prec.getRowCount()-1,4);
                            modelo_cruce_prec.setValueAt(new Float("0"),cruce_prec.getRowCount()-1,5);
                            total_2=r.getFloat("TOTAL");
                            modelo_cruce_prec.setValueAt(total_2,cruce_prec.getRowCount()-1,6);
                            modelo_cruce_prec.setValueAt(total_2-total_1,cruce_prec.getRowCount()-1,7);
                        }
                        con.cerrar();
                    }catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
                        con.cerrar();
                    }
                }else if(prec_defs.getValueAt(prec_defs.getSelectedRow()-1, 4).toString().equals("SI")){
                    while(cruce_prec.getRowCount()!=0){
                        modelo_cruce_prec.removeRow(cruce_prec.getRowCount()-1);
                    }
                    Conexion con = new Conexion();
                    Conexion con1 = new Conexion();
                    con.conexion();
                    con1.conexion();
                    String id_empresa ="";
                    try {
                        ResultSet r,r1;
                        r = con.s.executeQuery ("SELECT * "
                                + "FROM t_det_precalculos INNER JOIN t_empresas ON (t_det_precalculos.ID_EMPRESA = t_empresas.ID_EMPRESA) "
                                + "WHERE ID_PREC = "+prec_defs.getValueAt(prec_defs.getSelectedRow(), 0)+" "
                                + "ORDER BY t_det_precalculos.ID_EMPRESA ASC");
                        while (r.next()) {
                            modelo_cruce_prec.addRow(new Object[8]);
                            id_empresa=r.getString("ID_EMPRESA");
                            modelo_cruce_prec.setValueAt(id_empresa,cruce_prec.getRowCount()-1,0);
                            modelo_cruce_prec.setValueAt(r.getString("NOMBRE_EMPRESA"),cruce_prec.getRowCount()-1,1);
                            /////////*************************************************************************
                            r1 = con1.s.executeQuery ("SELECT * "
                                + "FROM t_det_precalculos INNER JOIN t_empresas ON (t_det_precalculos.ID_EMPRESA = t_empresas.ID_EMPRESA) "
                                + "WHERE ID_PREC = "+prec_defs.getValueAt(prec_defs.getSelectedRow()-1, 0)+" AND t_det_precalculos.ID_EMPRESA ='"+id_empresa+"'");
                            if (r1.next()) {
                                fic_1=r1.getFloat("FIC");
                                total_1=r1.getFloat("TOTAL");
                                modelo_cruce_prec.setValueAt(fic_1,cruce_prec.getRowCount()-1,2);
                                modelo_cruce_prec.setValueAt(total_1,cruce_prec.getRowCount()-1,5);
                            }else{
                                fic_1=0;
                                total_1=0;
                                modelo_cruce_prec.setValueAt(fic_1,cruce_prec.getRowCount()-1,2);
                                modelo_cruce_prec.setValueAt(total_1,cruce_prec.getRowCount()-1,5);
                            }
                            /////////*************************************************************************
                            fic_2 =r.getFloat("FIC");
                            modelo_cruce_prec.setValueAt(fic_2,cruce_prec.getRowCount()-1,3);
                            ////////////**********************************************************************
                            modelo_cruce_prec.setValueAt(fic_2-fic_1,cruce_prec.getRowCount()-1,4);
                            /////////*************************************************************************
                            total_2=r.getFloat("TOTAL");
                            modelo_cruce_prec.setValueAt(total_2,cruce_prec.getRowCount()-1,6);
                            modelo_cruce_prec.setValueAt(total_2-total_1,cruce_prec.getRowCount()-1,7);
                        }
                        con.cerrar();
                    }catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
                        con.cerrar();
                    }    
                }else{
                    JOptionPane.showMessageDialog(this,"Para calcular el cruce del precalculo seleccionado debe\ngenerar el Cruce del precalculo anterior","Error",JOptionPane.ERROR_MESSAGE);
                }
                registros.setText(String.valueOf(cruce_prec.getRowCount()));
            }else{
                JOptionPane.showMessageDialog(this,"El registro seleccionado no debe tener ningun Cruce generado anteriormente","Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un registro en la tabla de Precalculos Definitivos","Error",JOptionPane.ERROR_MESSAGE);
        }
    
    }
}
