/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.Conexion;
import java.awt.Event;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author ADMIN
 */
public class Edd_Empresa extends javax.swing.JDialog {
    boolean perm=false;
    boolean perm_mun=false;
    /**
     * Creates new form Edd_Empresa1
     */
    public Edd_Empresa(java.awt.Frame parent, boolean modal, String n) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        ac_tip_nit();
        ac_nit();
        ac_arl();
        ac_ccf();
        ac_act();
        ac_dep();
        ac_mun(cb_dep.getSelectedItem().toString());
        ac_tamaño();
        InputMap map1 = nit.getInputMap(nit.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        perm=true;
        perm_mun=true;
        if (!n.equals("")) {
            load_data(n);
            cb_nit.setEnabled(false);
        }
    }
    public Edd_Empresa(javax.swing.JDialog parent, boolean modal, String n) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        ac_tip_nit();
        ac_nit();
        ac_arl();
        ac_ccf();
        ac_act();
        ac_dep();
        ac_mun(cb_dep.getSelectedItem().toString());
        ac_tamaño();
        InputMap map1 = nit.getInputMap(nit.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        perm=true;
        perm_mun=true;
        if (!n.equals("")) {
            load_data(n);
            cb_nit.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre_empresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_nit = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cb_arl = new javax.swing.JComboBox<>();
        cb_ccf = new javax.swing.JComboBox<>();
        add_arl = new javax.swing.JButton();
        add_ccf = new javax.swing.JButton();
        edd_arl = new javax.swing.JButton();
        add_ccf1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cb_actividad = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cb_tip_nit = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        representante = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefonos = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tb_id_rl = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        correo_interno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        correo_1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        correo_2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        correo_3 = new javax.swing.JTextField();
        sel_1 = new javax.swing.JCheckBox();
        sel_3 = new javax.swing.JCheckBox();
        sel_2 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        sel_int = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dir_empresa = new javax.swing.JTextField();
        cb_dep = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cb_mun = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tel_empresa = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cb_tamaño = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        reg_mercantil = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        f_ren_reg_mercantil = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        f_limit_seg_empresa = new com.toedter.components.JSpinField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Empresa");
        setResizable(false);
        setSize(new java.awt.Dimension(549, 162));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de la empresa"));

        jLabel1.setText("Nombre Empresa");

        nombre_empresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_empresaKeyTyped(evt);
            }
        });

        jLabel2.setText("NIT");

        nit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nitKeyTyped(evt);
            }
        });

        jLabel3.setText("Nuevo NIT");

        //AutoCompletion.enable(cb_nit);
        cb_nit.setEnabled(false);
        cb_nit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_nitItemStateChanged(evt);
            }
        });
        cb_nit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cb_nitKeyReleased(evt);
            }
        });

        jLabel9.setText("ARL");

        jLabel21.setText("CCF");

        //AutoCompletion.enable(cb_arl);

        //AutoCompletion.enable(cb_ccf);

        add_arl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/link_add.png"))); // NOI18N
        add_arl.setToolTipText("Agregar ARL");
        add_arl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_arlActionPerformed(evt);
            }
        });

        add_ccf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart_add.png"))); // NOI18N
        add_ccf.setToolTipText("Agregar CCF");
        add_ccf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ccfActionPerformed(evt);
            }
        });

        edd_arl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/link_edit.png"))); // NOI18N
        edd_arl.setToolTipText("Editar ARL");
        edd_arl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edd_arlActionPerformed(evt);
            }
        });

        add_ccf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart_half.png"))); // NOI18N
        add_ccf1.setToolTipText("Editar CCF");
        add_ccf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ccf1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Actividad");

        //AutoCompletion.enable(cb_actividad);

        jLabel17.setText("Tipo NIT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel21)
                            .addComponent(jLabel12))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cb_ccf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_arl, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_ccf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_arl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cb_actividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_ccf1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edd_arl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nit, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cb_tip_nit, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_nit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(190, 190, 190))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tip_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cb_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel9)
                            .addComponent(add_arl)
                            .addComponent(cb_arl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel21)
                            .addComponent(add_ccf)
                            .addComponent(cb_ccf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edd_arl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_ccf1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cb_actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accept_1.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_1.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos adicionales"));

        jLabel8.setText("Representante legal");

        representante.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setText("Telefonos");

        telefonos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefonos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonosKeyTyped(evt);
            }
        });

        jLabel22.setText("Cedula");

        tb_id_rl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tb_id_rl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tb_id_rlKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb_id_rl, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(telefonos)
                        .addComponent(representante, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_id_rl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(telefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de correo"));

        jLabel4.setText("Correo interno");

        correo_interno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Correo contratista 1");

        correo_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Correo contratista 2");

        correo_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setText("Correo contratista 3");

        correo_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setText("Sel.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correo_3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo_2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(correo_interno)
                        .addComponent(correo_1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(sel_1)
                        .addComponent(sel_2)
                        .addComponent(sel_3))
                    .addComponent(sel_int))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(correo_interno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(sel_int))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(correo_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sel_1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(correo_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(sel_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(correo_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(sel_3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de ubicación"));

        jLabel13.setText("Direccion");

        dir_empresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cb_dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cb_dep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_depItemStateChanged(evt);
            }
        });

        jLabel14.setText("Departamento");

        cb_mun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel15.setText("Ciudad");

        jLabel16.setText("Teléfono");

        tel_empresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tel_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tel_empresaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_mun, 0, 207, Short.MAX_VALUE)
                    .addComponent(cb_dep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dir_empresa)
                    .addComponent(tel_empresa))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dir_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño Empresa"));

        jLabel18.setText("No Empleados");

        cb_tamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(cb_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Registro Mercantil"));

        jLabel19.setText("Registro Mercantil");

        reg_mercantil.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel20.setText("Fecha Renovación");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_ren_reg_mercantil, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reg_mercantil, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(reg_mercantil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(f_ren_reg_mercantil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Seguridad Social"));

        jLabel23.setText("Fecha limite");

        f_limit_seg_empresa.setMaximum(30);
        f_limit_seg_empresa.setMinimum(1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(f_limit_seg_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(f_limit_seg_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_empresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_empresaKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        a = Character.toUpperCase(a);
        System.out.println(evt.getKeyCode());
        if(!(a>=KeyEvent.VK_A && a<=KeyEvent.VK_Z) & a!=KeyEvent.VK_SPACE & a!=209) {
            evt.consume();
        }
        if(nombre_empresa.getText().length()>50){
            evt.consume();
        }

    }//GEN-LAST:event_nombre_empresaKeyTyped

    private void nitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nitKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if(a!=KeyEvent.VK_MINUS){
            if(!(a>=KeyEvent.VK_0 && a<=KeyEvent.VK_9)) {
                evt.consume();
            }
        }
        if(nit.getText().length()>15){
            evt.consume();
        }
    }//GEN-LAST:event_nitKeyTyped

    private void cb_nitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_nitItemStateChanged
        // TODO add your handling code here:
        load_data();
    }//GEN-LAST:event_cb_nitItemStateChanged

    private void cb_nitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_nitKeyReleased
        // TODO add your handling code here:
        int b=evt.getKeyCode();
        if(b==KeyEvent.VK_ENTER){
            load_data();
        }
    }//GEN-LAST:event_cb_nitKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (!cb_tip_nit.getSelectedItem().equals("Seleccione..")) {
            if (!nit.getText().equals("")) {
                if (!nombre_empresa.getText().equals("")) {
                    if (!cb_arl.getSelectedItem().equals("Seleccione..")) {
                        if (!cb_ccf.getSelectedItem().equals("Seleccione..")) {
                            if (!cb_actividad.getSelectedItem().equals("Seleccione..")) {
                                if (!tb_id_rl.getText().equals("")) {
                                    if (!representante.getText().equals("")) {
                                        if (!telefonos.getText().equals("")) {
                                            if (check_mail(correo_interno.getText())) {
                                                if (check_mail(correo_1.getText())) {
                                                    if (check_mail(correo_2.getText())) {
                                                        if (check_mail(correo_3.getText())) {
                                                            if (sel_int.isSelected() | sel_1.isSelected() | sel_2.isSelected() | sel_3.isSelected()) {
                                                                if (!(correo_interno.getText().equals("") & sel_int.isSelected())) {
                                                                    if (!(correo_1.getText().equals("") & sel_1.isSelected())) {
                                                                        if (!(correo_2.getText().equals("") & sel_2.isSelected())) {
                                                                            if (!(correo_3.getText().equals("") & sel_3.isSelected())) {
                                                                                if (!tel_empresa.getText().equals("")) {
                                                                                    if (!dir_empresa.getText().equals("")) {
                                                                                        if (!cb_dep.getSelectedItem().equals("Seleccione..")) {
                                                                                            if (!cb_mun.getSelectedItem().equals("Seleccione..")) {
                                                                                                if (!cb_tamaño.getSelectedItem().equals("Seleccione..")) {
                                                                                                    if (!reg_mercantil.getText().equals("")) {
                                                                                                        if (f_ren_reg_mercantil.getDate()!=null){   
                                                                                                            if (f_limit_seg_empresa.getValue()>0 & f_limit_seg_empresa.getValue()<=30) {
                                                                                                                Conexion con = new Conexion();
                                                                                                                con.conexion();
                                                                                                                ResultSet r;
                                                                                                                try {
                                                                                                                    r = con.s.executeQuery ("SELECT * FROM `t_empresas` WHERE ID_EMPRESA = '"+cb_nit.getSelectedItem()+"'");
                                                                                                                    if(!r.next()){
                                                                                                                        JOptionPane.showMessageDialog(this,"La empresa que intenta ingresar no existe","Error",JOptionPane.ERROR_MESSAGE);
                                                                                                                    }
                                                                                                                    else{
                                                                                                                        int conf = JOptionPane.showConfirmDialog(this,"Esta seguro que desea continuar?","Confirmación",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
                                                                                                                        if (conf == JOptionPane.YES_OPTION) {
                                                                                                                            int id_tip_nit = 0;
                                                                                                                            int id_arl = 0;
                                                                                                                            int id_ccf = 0;
                                                                                                                            int id_act = 0;
                                                                                                                            int id_mun =0;
                                                                                                                            int id_tam=0;
                                                                                                                            r = con.s.executeQuery ("SELECT ID_TIPO_NIT FROM `t_tipo_nit` WHERE NOMBRE_TIPO_NIT ='"+cb_tip_nit.getSelectedItem().toString()+"';");
                                                                                                                            if(r.next()){
                                                                                                                                id_tip_nit=r.getInt("ID_TIPO_NIT");    
                                                                                                                            }
                                                                                                                            r = con.s.executeQuery ("SELECT ID_ARL FROM `t_arl` WHERE (NOMBRE_ARL ='"+cb_arl.getSelectedItem().toString()+"');");
                                                                                                                            if(r.next()){
                                                                                                                                id_arl=r.getInt("ID_ARL");    
                                                                                                                            }
                                                                                                                            r = con.s.executeQuery ("SELECT ID_CCF FROM `t_ccf` WHERE (NOMBRE_CCF ='"+cb_ccf.getSelectedItem().toString()+"');");
                                                                                                                            if(r.next()){
                                                                                                                                id_ccf=r.getInt("ID_CCF");    
                                                                                                                            }
                                                                                                                            r = con.s.executeQuery ("SELECT ID_ACTIVIDAD FROM `t_actividades` WHERE NOMBRE_ACTIVIDAD ='"+cb_actividad.getSelectedItem().toString()+"';");
                                                                                                                            if(r.next()){
                                                                                                                                id_act=r.getInt("ID_ACTIVIDAD");    
                                                                                                                            }
                                                                                                                            r = con.s.executeQuery ("SELECT * FROM t_municipios WHERE NOMBRE_MUN = '"+cb_mun.getSelectedItem()+"';");
                                                                                                                            if(r.next()){
                                                                                                                                id_mun=r.getInt("ID_MUN");
                                                                                                                            }
                                                                                                                            r = con.s.executeQuery ("SELECT ID_TAMAÑO FROM t_tamaño_empresa WHERE NOMBRE_TAMAÑO = '"+cb_tamaño.getSelectedItem()+"';");
                                                                                                                            if(r.next()){
                                                                                                                                id_tam=r.getInt("ID_TAMAÑO");
                                                                                                                            }
                                                                                                                            con.s.executeUpdate("update `t_empresas`\n" +
                                                                                                                                                "set `ID_TIPO_NIT` = "+id_tip_nit+",\n" +
                                                                                                                                                "  `ID_EMPRESA` = '"+nit.getText()+"',\n" +
                                                                                                                                                "  `NOMBRE_EMPRESA` = '"+nombre_empresa.getText()+"',\n" +
                                                                                                                                                "  `ID_ARL` = '"+id_arl+"',\n" +
                                                                                                                                                "  `ID_CCF` = '"+id_ccf+"',\n" +
                                                                                                                                                "  `ID_ACTIVIDAD` = "+id_act+",\n" +
                                                                                                                                                "  `ID_REP_EMPRESA` = "+tb_id_rl.getText()+",\n" +
                                                                                                                                                "  `REPRESENTANTE_LEGAL` = '"+representante.getText().toUpperCase()+"',\n" +
                                                                                                                                                "  `TEL_CEL_RL_EMPRESA` = '"+telefonos.getText()+"',\n" +
                                                                                                                                                "  `CORREO_INTERNO` = '"+correo_interno.getText()+"',\n" +
                                                                                                                                                "  `CORREO_CONTRATISTA_1` = '"+correo_1.getText()+"',\n" +
                                                                                                                                                "  `CORREO_CONTRATISTA_2` = '"+correo_2.getText()+"',\n" +
                                                                                                                                                "  `CORREO_CONTRATISTA_3` = '"+correo_3.getText()+"',\n" +
                                                                                                                                                "  `ENABLE_INTERNO` = "+bool_to_int(sel_int.isSelected())+",\n" +
                                                                                                                                                "  `ENABLE_1` = "+bool_to_int(sel_1.isSelected())+",\n" +
                                                                                                                                                "  `ENABLE_2` = "+bool_to_int(sel_2.isSelected())+",\n" +
                                                                                                                                                "  `ENABLE_3` = "+bool_to_int(sel_3.isSelected())+",\n" +
                                                                                                                                                "  `TEL_CEL_EMPRESA` = '"+tel_empresa.getText()+"',\n" +
                                                                                                                                                "  `DIR_EMPRESA` = '"+dir_empresa.getText()+"',\n" +
                                                                                                                                                "  `ID_MUN_EMPRESA` = "+id_mun+",\n" +
                                                                                                                                                "  `ID_TAM_EMPRESA` = "+id_tam+",\n" +
                                                                                                                                                "  `REG_MER_EMPRESA` = '"+reg_mercantil.getText().trim()+"',\n" +
                                                                                                                                                "  `F_REN_REG_MERC` = '"+new SimpleDateFormat("yyyy-MM-dd").format(f_ren_reg_mercantil.getDate())+"',\n" +
                                                                                                                                                "  `F_LIM_SEG` = '"+f_limit_seg_empresa.getValue()+"'\n" +
                                                                                                                                                "   WHERE `ID_EMPRESA` = '"+cb_nit.getSelectedItem().toString()+"';");
                                                                                                                            //con.s.executeUpdate("UPDATE `t_empresas` SET `ID_TIPO_NIT`="+id_tip_nit+",`ID_EMPRESA`='"+nit.getText()+"',`NOMBRE_EMPRESA`='"+nombre_empresa.getText()+"',`ID_ARL`='"+id_arl+"',`ID_CCF`='"+id_ccf+"',`ID_ACTIVIDAD`="+id_act+",`ID_REP_EMPRESA`='"+tb_id_rl.getText()+"',`REPRESENTANTE_LEGAL`='"+representante.getText().toUpperCase()+"',`TEL_CEL_RL_EMPRESA`='"+telefonos.getText()+"',CORREO_INTERNO = '"+correo_interno.getText()+"', CORREO_CONTRATISTA_1 = '"+correo_1.getText()+"', CORREO_CONTRATISTA_2 = '"+correo_2.getText()+"', CORREO_CONTRATISTA_3 = '"+correo_3.getText()+"', ENABLE_INTERNO = "+bool_to_int(sel_int.isSelected())+", ENABLE_1 = "+bool_to_int(sel_1.isSelected())+", ENABLE_2 = "+bool_to_int(sel_2.isSelected())+", ENABLE_3 = "+bool_to_int(sel_3.isSelected())+",`TEL_CEL_EMPRESA`='"+tel_empresa.getText()+"',`DIR_EMPRESA`='"+dir_empresa.getText()+"',`ID_MUN_EMPRESA`="+id_mun+",`ID_TAM_EMPRESA`="+id_tam+",`REG_MER_EMPRESA`='"+reg_mercantil.getText().trim()+"',`F_REN_REG_MERC`='"+new SimpleDateFormat("yyyy-MM-dd").format(f_ren_reg_mercantil.getDate())+"' WHERE ID_EMPRESA = '"+cb_nit.getSelectedItem().toString()+"'");
                                                                                                                            JOptionPane.showMessageDialog(this,"La empresa fue modificada correctamente","Información",JOptionPane.INFORMATION_MESSAGE);
                                                                                                                            con.cerrar();
                                                                                                                            this.dispose();
                                                                                                                        }
                                                                                                                    }
                                                                                                                    con.cerrar();
                                                                                                                } catch (SQLException | HeadlessException e) {
                                                                                                                    con.cerrar();
                                                                                                                    e.printStackTrace();
                                                                                                                    JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
                                                                                                                }
                                                                                                            }else{
                                                                                                                f_limit_seg_empresa.requestFocus();
                                                                                                                JOptionPane.showMessageDialog(this,"Ingrese la fecha limite de seguridad social de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                                                                            }
                                                                                                            
                                                                                                        } else {
                                                                                                            f_ren_reg_mercantil.requestFocus();
                                                                                                            JOptionPane.showMessageDialog(this,"Ingrese la fecha de renovación del registro mercantil de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                                                                        }
                                                                                                    } else {
                                                                                                        cb_tamaño.requestFocus();
                                                                                                        JOptionPane.showMessageDialog(this,"Ingrese el registro mercantil de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                                                                    }
                                                                                                } else {
                                                                                                    cb_tamaño.requestFocus();
                                                                                                    JOptionPane.showMessageDialog(this,"Seleccione el tamaño de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                                                                }
                                                                                            } else {
                                                                                                cb_mun.requestFocus();
                                                                                                JOptionPane.showMessageDialog(this,"Seleccione el municipio donde se ubica la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                                                            }
                                                                                        } else {
                                                                                            cb_dep.requestFocus();
                                                                                            JOptionPane.showMessageDialog(this,"Seleccione el departamento donde se ubica la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                                                        }

                                                                                    } else {
                                                                                        dir_empresa.requestFocus();
                                                                                        JOptionPane.showMessageDialog(this,"Ingrese la dirección de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                                                    }
                                                                                } else {
                                                                                    tel_empresa.requestFocus();
                                                                                    JOptionPane.showMessageDialog(this,"Ingrese el teléfono de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                                                }
                                                                            }else{
                                                                                sel_3.requestFocus();
                                                                                JOptionPane.showMessageDialog(this,"No se debe seleccionar un correo no valido","Error",JOptionPane.ERROR_MESSAGE);
                                                                            }
                                                                        }else{
                                                                            sel_2.requestFocus();
                                                                            JOptionPane.showMessageDialog(this,"No se debe seleccionar un correo no valido","Error",JOptionPane.ERROR_MESSAGE);
                                                                        }
                                                                    }else{
                                                                        sel_1.requestFocus();
                                                                        JOptionPane.showMessageDialog(this,"No se debe seleccionar un correo no valido","Error",JOptionPane.ERROR_MESSAGE);
                                                                    }
                                                                }else{
                                                                    sel_int.requestFocus();
                                                                    JOptionPane.showMessageDialog(this,"No se debe seleccionar un correo no valido","Error",JOptionPane.ERROR_MESSAGE);
                                                                }
                                                            }else{
                                                                JOptionPane.showMessageDialog(this,"Seleccione al menos una direccion de correo para el envio automatico de informes.","Error",JOptionPane.ERROR_MESSAGE);
                                                            }
                                                        }else{
                                                            correo_3.requestFocus();
                                                            JOptionPane.showMessageDialog(this,"Verifique el correo alterno 3 de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                        }
                                                    }else{
                                                        correo_2.requestFocus();
                                                        JOptionPane.showMessageDialog(this,"Verifique el correo alterno 2 de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                    }
                                                }else{
                                                    correo_1.requestFocus();
                                                    JOptionPane.showMessageDialog(this,"Verifique el correo alterno 1 de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                                }
                                            }else{
                                                correo_interno.requestFocus();
                                                JOptionPane.showMessageDialog(this,"Verifique el correo interno de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                            }
                                        } else {
                                            tb_id_rl.requestFocus();
                                            JOptionPane.showMessageDialog(this,"Ingrese los telefonos del representante legal de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                        }
                                    } else {
                                        tb_id_rl.requestFocus();
                                        JOptionPane.showMessageDialog(this,"Ingrese el nombre del representante legal de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                    }
                                } else {
                                    tb_id_rl.requestFocus();
                                    JOptionPane.showMessageDialog(this,"Ingrese la identificacion o NIT del representante legal de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                }
                            }else{
                                cb_actividad.requestFocus();
                                JOptionPane.showMessageDialog(this,"Seleccione la Actividad de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                            }
                        }else {
                            cb_ccf.requestFocus();
                            JOptionPane.showMessageDialog(this,"Seleccione la CCF de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                        }
                    }else {
                        cb_arl.requestFocus();
                        JOptionPane.showMessageDialog(this,"Seleccione la ARL de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,"Digite el nombre de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,"Digite el NIT de la empresa","Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            cb_actividad.requestFocus();
            JOptionPane.showMessageDialog(this,"Seleccione el tipo de nit de la empresa","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void add_arlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_arlActionPerformed
        // TODO add your handling code here:
        Add_ARL add_arl = new Add_ARL(this, true);
        add_arl.setLocationRelativeTo(this);
        add_arl.setVisible(true);
    }//GEN-LAST:event_add_arlActionPerformed

    private void add_ccfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ccfActionPerformed
        // TODO add your handling code here:
        Add_CCF add_ccf = new Add_CCF(this, true);
        add_ccf.setLocationRelativeTo(this);
        add_ccf.setVisible(true);
    }//GEN-LAST:event_add_ccfActionPerformed

    private void edd_arlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edd_arlActionPerformed
        // TODO add your handling code here:
        Edd_ARL edd_arl = new Edd_ARL(this, true);
        edd_arl.setLocationRelativeTo(this);
        edd_arl.setVisible(true);
    }//GEN-LAST:event_edd_arlActionPerformed

    private void add_ccf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ccf1ActionPerformed
        // TODO add your handling code here:
        Edd_CCF edd_ccf = new Edd_CCF(this, true);
        edd_ccf.setLocationRelativeTo(this);
        edd_ccf.setVisible(true);
    }//GEN-LAST:event_add_ccf1ActionPerformed

    private void telefonosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonosKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if(a!=KeyEvent.VK_MINUS){
            if(!(a>=KeyEvent.VK_0 && a<=KeyEvent.VK_9)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_telefonosKeyTyped

    private void cb_depItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_depItemStateChanged
        // TODO add your handling code here:
        if (perm) {
            //perm_mun=false;
            ac_mun(cb_dep.getSelectedItem().toString());
            //perm_mun=true;
        }
    }//GEN-LAST:event_cb_depItemStateChanged

    private void tel_empresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tel_empresaKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if(a!=KeyEvent.VK_MINUS){
            if(!(a>=KeyEvent.VK_0 && a<=KeyEvent.VK_9)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_tel_empresaKeyTyped

    private void tb_id_rlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_id_rlKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if(a!=KeyEvent.VK_MINUS){
            if(!(a>=KeyEvent.VK_0 && a<=KeyEvent.VK_9)) {
                evt.consume();
            }
        }
        if(nit.getText().length()>15){
            evt.consume();
        }
    }//GEN-LAST:event_tb_id_rlKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edd_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edd_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edd_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edd_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Edd_Empresa dialog = new Edd_Empresa(new javax.swing.JFrame(), true, new String());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_arl;
    private javax.swing.JButton add_ccf;
    private javax.swing.JButton add_ccf1;
    private javax.swing.JComboBox<String> cb_actividad;
    private javax.swing.JComboBox<String> cb_arl;
    private javax.swing.JComboBox<String> cb_ccf;
    private javax.swing.JComboBox<String> cb_dep;
    private javax.swing.JComboBox<String> cb_mun;
    private javax.swing.JComboBox<String> cb_nit;
    private javax.swing.JComboBox<String> cb_tamaño;
    private javax.swing.JComboBox<String> cb_tip_nit;
    private javax.swing.JTextField correo_1;
    private javax.swing.JTextField correo_2;
    private javax.swing.JTextField correo_3;
    private javax.swing.JTextField correo_interno;
    private javax.swing.JTextField dir_empresa;
    private javax.swing.JButton edd_arl;
    private com.toedter.components.JSpinField f_limit_seg_empresa;
    private com.toedter.calendar.JDateChooser f_ren_reg_mercantil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private static javax.swing.JTextField nit;
    private static javax.swing.JTextField nombre_empresa;
    private javax.swing.JTextField reg_mercantil;
    private javax.swing.JTextField representante;
    private javax.swing.JCheckBox sel_1;
    private javax.swing.JCheckBox sel_2;
    private javax.swing.JCheckBox sel_3;
    private javax.swing.JCheckBox sel_int;
    private javax.swing.JTextField tb_id_rl;
    private javax.swing.JTextField tel_empresa;
    private javax.swing.JTextField telefonos;
    // End of variables declaration//GEN-END:variables
public void load_data(){
    if (!cb_nit.getSelectedItem().equals("Seleccione..")) {
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try {
            r = con.s.executeQuery ("SELECT *\n" +
                                    "FROM\n" +
                                    "    t_empresas\n" +
                                    "    INNER JOIN t_arl \n" +
                                    "        ON (t_empresas.ID_ARL = t_arl.ID_ARL)\n" +
                                    "    INNER JOIN t_ccf \n" +
                                    "        ON (t_empresas.ID_CCF = t_ccf.ID_CCF)\n" +
                                    "    INNER JOIN t_actividades \n" +
                                    "        ON (t_empresas.ID_ACTIVIDAD = t_actividades.ID_ACTIVIDAD) WHERE t_empresas.ID_EMPRESA = '"+cb_nit.getSelectedItem()+"'");
            if (r.next()) {
                //cb_nit.setSelectedItem(r.getString("ID_EMPRESA"));
                nombre_empresa.setText(r.getString("NOMBRE_EMPRESA"));
                nit.setText(r.getString("ID_EMPRESA"));
                cb_arl.setSelectedItem(r.getString("NOMBRE_ARL"));
                cb_ccf.setSelectedItem(r.getString("NOMBRE_CCF"));
                cb_actividad.setSelectedItem(r.getString("NOMBRE_ACTIVIDAD"));
                representante.setText(r.getString("REPRESENTANTE_LEGAL"));
                telefonos.setText(r.getString("TEL_CEL_EMPRESA"));
                correo_interno.setText(r.getString("CORREO_INTERNO"));
                correo_1.setText(r.getString("CORREO_CONTRATISTA_1"));
                correo_2.setText(r.getString("CORREO_CONTRATISTA_2"));
                correo_3.setText(r.getString("CORREO_CONTRATISTA_3"));
                if (r.getString("ENABLE_INTERNO").equals("1")) {
                    sel_int.setSelected(true);
                }else{
                    sel_int.setSelected(false);
                }
                if (r.getString("ENABLE_1").equals("1")) {
                    sel_1.setSelected(true);
                }else{
                    sel_1.setSelected(false);
                }
                if (r.getString("ENABLE_2").equals("1")) {
                    sel_2.setSelected(true);
                }else{
                    sel_2.setSelected(false);
                }
                if (r.getString("ENABLE_3").equals("1")) {
                    sel_3.setSelected(true);
                }else{
                    sel_3.setSelected(false);
                }
            }
            con.cerrar();
        }catch(SQLException j){
            con.cerrar();
            j.printStackTrace();
            JOptionPane.showMessageDialog(this,j,"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    else{
        nombre_empresa.setText("");
        nit.setText("");
    }
}
private void load_data(String n){
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try {
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    `t_empresas`\n" +
                                "    INNER JOIN `t_tipo_nit` \n" +
                                "        ON (`t_empresas`.`ID_TIPO_NIT` = `t_tipo_nit`.`ID_TIPO_NIT`)\n" +
                                "    INNER JOIN `t_arl` \n" +
                                "        ON (`t_empresas`.`ID_ARL` = `t_arl`.`ID_ARL`)\n" +
                                "    INNER JOIN `t_ccf` \n" +
                                "        ON (`t_empresas`.`ID_CCF` = `t_ccf`.`ID_CCF`)\n" +
                                "    INNER JOIN `t_actividades` \n" +
                                "        ON (`t_empresas`.`ID_ACTIVIDAD` = `t_actividades`.`ID_ACTIVIDAD`)\n" +
                                "    INNER JOIN `t_municipios` \n" +
                                "        ON (`t_empresas`.`ID_MUN_EMPRESA` = `t_municipios`.`ID_MUN`)\n" +
                                "    INNER JOIN `t_departamentos` \n" +
                                "        ON (`t_municipios`.`ID_DEP` = `t_departamentos`.`ID_DEP`)\n" +
                                "    INNER JOIN `t_tamaño_empresa` \n" +
                                "        ON (`t_empresas`.`ID_TAM_EMPRESA` = `t_tamaño_empresa`.`ID_TAMAÑO`) WHERE t_empresas.ID_EMPRESA = '"+n+"'");
        if (r.next()) {
            cb_tip_nit.setSelectedItem(r.getString("NOMBRE_TIPO_NIT"));
            cb_nit.setSelectedItem(r.getString("ID_EMPRESA"));
            nit.setText(r.getString("ID_EMPRESA"));
            nombre_empresa.setText(r.getString("NOMBRE_EMPRESA"));
            cb_arl.setSelectedItem(r.getString("NOMBRE_ARL"));
            cb_ccf.setSelectedItem(r.getString("NOMBRE_CCF"));
            cb_actividad.setSelectedItem(r.getString("NOMBRE_ACTIVIDAD"));
            tb_id_rl.setText(r.getString("ID_REP_EMPRESA"));
            representante.setText(r.getString("REPRESENTANTE_LEGAL"));
            telefonos.setText(r.getString("TEL_CEL_RL_EMPRESA"));
            correo_interno.setText(r.getString("CORREO_INTERNO"));
            correo_1.setText(r.getString("CORREO_CONTRATISTA_1"));
            correo_2.setText(r.getString("CORREO_CONTRATISTA_2"));
            correo_3.setText(r.getString("CORREO_CONTRATISTA_3"));
            if (r.getString("ENABLE_INTERNO").equals("1")) {
                sel_int.setSelected(true);
            }else{
                sel_int.setSelected(false);
            }
            if (r.getString("ENABLE_1").equals("1")) {
                sel_1.setSelected(true);
            }else{
                sel_1.setSelected(false);
            }
            if (r.getString("ENABLE_2").equals("1")) {
                sel_2.setSelected(true);
            }else{
                sel_2.setSelected(false);
            }
            if (r.getString("ENABLE_3").equals("1")) {
                sel_3.setSelected(true);
            }else{
                sel_3.setSelected(false);
            }
            tel_empresa.setText(r.getString("TEL_CEL_EMPRESA"));
            dir_empresa.setText(r.getString("DIR_EMPRESA"));
            cb_dep.setSelectedItem(r.getString("NOMBRE_DEP"));
            cb_mun.setSelectedItem(r.getString("NOMBRE_MUN"));
            cb_tamaño.setSelectedItem(r.getString("NOMBRE_TAMAÑO"));
            reg_mercantil.setText(r.getString("REG_MER_EMPRESA"));
            f_ren_reg_mercantil.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(r.getString("F_REN_REG_MERC")));
            f_limit_seg_empresa.setValue(r.getInt("F_LIM_SEG"));
        }
        con.cerrar();
    }catch(ParseException  | SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(this,j,"Error",JOptionPane.ERROR_MESSAGE);
    }


}
public final void ac_tip_nit(){
    cb_tip_nit.removeAllItems();
    cb_tip_nit.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM `t_tipo_nit` ORDER BY NOMBRE_TIPO_NIT ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_TIPO_NIT");
            cb_tip_nit.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}  
public final void ac_nit(){
    cb_nit.removeAllItems();
    cb_nit.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_EMPRESAS ORDER BY ID_EMPRESA ASC;");
        while(r.next()){
            String str=r.getString("ID_EMPRESA");
            cb_nit.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}   
public final void ac_arl(){
    cb_arl.removeAllItems();
    cb_arl.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_ARL ORDER BY NOMBRE_ARL ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_ARL");
            cb_arl.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }

}
public final void ac_ccf(){
    cb_ccf.removeAllItems();
    cb_ccf.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_CCF ORDER BY NOMBRE_CCF ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_CCF");
            cb_ccf.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }

}
public final void ac_act(){
    cb_actividad.removeAllItems();
    cb_actividad.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_ACTIVIDADES ORDER BY NOMBRE_ACTIVIDAD ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_ACTIVIDAD");
            cb_actividad.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}  
public final void ac_dep(){
    cb_dep.removeAllItems();
    cb_dep.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_departamentos ORDER BY NOMBRE_DEP ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_DEP");
            cb_dep.addItem(str);
            
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }

}
public final void ac_mun(String dep){
    cb_mun.removeAllItems();
    if (dep.equals("Seleccione..")) {
        cb_mun.addItem("Seleccione..");
    } else {
        cb_mun.addItem("Seleccione..");
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try{
            r = con.s.executeQuery ("SELECT *\n" +
                                    "FROM\n" +
                                    "    t_municipios\n" +
                                    "    INNER JOIN t_departamentos \n" +
                                    "        ON (t_municipios.ID_DEP = t_departamentos.ID_DEP) WHERE NOMBRE_DEP = '"+dep+"' ORDER BY NOMBRE_MUN ASC;");
            while(r.next()){
                String str=r.getString("NOMBRE_MUN");
                cb_mun.addItem(str);
            }
            con.cerrar();
        }catch(SQLException j){
            con.cerrar();
            JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

}
public final void ac_tamaño(){
    cb_tamaño.removeAllItems();
    cb_tamaño.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM `t_tamaño_empresa` ORDER BY NOMBRE_TAMAÑO ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_TAMAÑO");
            cb_tamaño.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}   
public boolean check_mail(String mail){
boolean ret=false;
    if (!mail.equals("")) {
        if (mail.contains("@") & count_char(mail, '@')==1) {
            return true;
        }
    }else{
        return true;
    }
return ret;
}
public int count_char(String str, char c){
    String pr=str.trim();
    char _toCompare=c;
    int veces=0;
    char []caracteres=pr.toCharArray();
    for(int i=0;i<=caracteres.length-1;i++){
        if(_toCompare ==caracteres[i]){
                veces++;
        }
}
    return veces;
}
public int bool_to_int(boolean b){
    if (b) {
        return 1;
    }else{
        return 0;
    }
}
}
