/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.Conexion;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Sel_Empleador_1_3 extends javax.swing.JDialog {
static DefaultTableModel modelo = new DefaultTableModel();
String ced=null;
String tip=null;
ArrayList<String> ret = new ArrayList<String>();
//String ret="";
    /**
     * Creates new form Sel_Empleador
     */
    public Sel_Empleador_1_3(javax.swing.JDialog parent, boolean modal, String c, String t) {
        super(parent, modal);
        this.ced=c;
        this.tip=t;
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        Object [] fila = new Object[3];
        modelo = (DefaultTableModel)empleadores.getModel(); 
        while(empleadores.getRowCount()!=0){
            modelo.removeRow(empleadores.getRowCount()-1);
        }
        empleadores.setModel(modelo);
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try {
            r = con.s.executeQuery ("SELECT * FROM t_empleados WHERE ID_EMP ="+this.ced);
            if (r.next()) {
                cedula.setText(r.getString("ID_EMP"));
                nom_ap.setText(r.getString("NOMBRE_1_EMP")+" "+r.getString("NOMBRE_2_EMP")+" "+r.getString("APELLIDO_1_EMP")+" "+r.getString("APELLIDO_2_EMP"));
            }
            r = con.s.executeQuery ("SELECT\n"
                + "*\n"
                + "FROM t_novedades\n"
                + "  INNER JOIN t_empleados\n"
                + "    ON (t_novedades.ID_EMPLEADO = t_empleados.ID_EMP)\n"
                + "  INNER JOIN t_empresas\n"
                + "    ON (t_novedades.ID_EMPRESA = t_empresas.ID_EMPRESA)\n"
                + "  INNER JOIN t_eps\n"
                + "    ON (t_novedades.ID_EPS = t_eps.ID_EPS)\n"
                + "  INNER JOIN t_afp\n"
                + "    ON (t_novedades.ID_AFP = t_afp.ID_AFP)\n"
//                + "  INNER JOIN t_municipios\n"
//                + "    ON (t_novedades.ID_MUN_NOV = t_municipios.ID_MUN)\n"
//                + "  INNER JOIN t_parentesco\n"
//                + "    ON (t_novedades.ID_PAR_ACU_NOV = t_parentesco.ID_PAR)\n"
                + "  INNER JOIN t_obra\n"
                + "    ON (t_novedades.ID_OBRA = t_obra.ID_OBRA)\n"
                + "  INNER JOIN t_tipo_novedad\n"
                + "    ON (t_novedades.ID_TIPO = t_tipo_novedad.ID_TIPO)\n"
                + "WHERE (ID_EMP = "+this.ced+" AND t_novedades.ID_TIPO IN (1,3))\n"
                + "ORDER BY FECHA_INGRESO DESC;");
            while(r.next()){
                modelo.addRow(fila);
                empleadores.setModel(modelo);
                modelo.setValueAt(r.getString("ID_EMPRESA"),empleadores.getRowCount()-1,0);
                modelo.setValueAt(r.getString("NOMBRE_EMPRESA"),empleadores.getRowCount()-1,1);
                modelo.setValueAt(r.getString("NOMBRE_TIPO"),empleadores.getRowCount()-1,2);
            }
            empleadores.changeSelection(0,0, false, false);
            empleadores.requestFocus();
            con.cerrar();
        } catch (SQLException e) {
            con.cerrar();
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nom_ap = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empleadores = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione el empleador");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del empleado"));

        jLabel1.setText("Cedula");

        cedula.setEditable(false);
        cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Nombres y apellidos");

        nom_ap.setEditable(false);
        nom_ap.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nom_ap))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nom_ap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dtos empleadores activos"));

        empleadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIT", "NOMBRE", "TIPO NOVEDAD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empleadores.getTableHeader().setReorderingAllowed(false);
        empleadores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empleadoresKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(empleadores);
        if (empleadores.getColumnModel().getColumnCount() > 0) {
            empleadores.getColumnModel().getColumn(0).setMinWidth(15);
            empleadores.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_1.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accept_1.png"))); // NOI18N
        jButton14.setText("Aceptar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        if (empleadores.getSelectedRow()==-1) {
            JOptionPane.showMessageDialog(this,"Seleccione un empleador","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            //modelo = (DefaultTableModel)empleadores.getModel();
            Conexion con = new Conexion();
            con.conexion();
            ResultSet r;
            try {
                r = con.s.executeQuery ("SELECT\n"
                    + "*\n"
                    + "FROM t_novedades\n"
                    + "  INNER JOIN t_empleados\n"
                    + "    ON (t_novedades.ID_EMPLEADO = t_empleados.ID_EMP)\n"
                    + "  INNER JOIN t_empresas\n"
                    + "    ON (t_novedades.ID_EMPRESA = t_empresas.ID_EMPRESA)\n"
                    + "  INNER JOIN t_eps\n"
                    + "    ON (t_novedades.ID_EPS = t_eps.ID_EPS)\n"
                    + "  INNER JOIN t_afp\n"
                    + "    ON (t_novedades.ID_AFP = t_afp.ID_AFP)\n"
                    + "  INNER JOIN t_municipios\n"
                    + "    ON (t_novedades.ID_MUN_NOV = t_municipios.ID_MUN)\n"
                    + "  INNER JOIN t_parentesco\n"
                    + "    ON (t_novedades.ID_PAR_ACU_NOV = t_parentesco.ID_PAR)\n"
                    + "  INNER JOIN t_obra\n"
                    + "    ON (t_novedades.ID_OBRA = t_obra.ID_OBRA)\n"
                    + "  INNER JOIN t_tipo_novedad\n"
                    + "    ON (t_novedades.ID_TIPO = t_tipo_novedad.ID_TIPO)\n"
                    + "WHERE (t_novedades.ID_EMPLEADO = "+this.ced+" AND t_novedades.ID_EMPRESA = "+modelo.getValueAt(empleadores.getSelectedRow(),0)+" AND t_tipo_novedad.NOMBRE_TIPO = '"+modelo.getValueAt(empleadores.getSelectedRow(),2)+"')\n"
                    + "ORDER BY FECHA_INGRESO DESC;");
                if(r.next()){
                    ret.add(r.getString("ID_EMP"));
                    ret.add(r.getString("ID_EMPRESA"));
                    ret.add(r.getString("FECHA_INGRESO"));
                    ret.add(r.getString("FECHA_RETIRO"));
                    ret.add(r.getString("ID_TIPO"));
                }
                con.cerrar();
            } catch (SQLException e) {
                con.cerrar();
                e.printStackTrace();
            }
            this.dispose();
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void empleadoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleadoresKeyPressed
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (a == KeyEvent.VK_ENTER) {
            if (empleadores.getSelectedRow()==-1) {
                JOptionPane.showMessageDialog(this,"Seleccione un empleador","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                //modelo = (DefaultTableModel)empleadores.getModel();
                Conexion con = new Conexion();
                con.conexion();
                ResultSet r;
                try {
                    r = con.s.executeQuery ("SELECT\n"
                        + "*\n"
                        + "FROM t_novedades\n"
                        + "  INNER JOIN t_empleados\n"
                        + "    ON (t_novedades.ID_EMPLEADO = t_empleados.ID_EMP)\n"
                        + "  INNER JOIN t_empresas\n"
                        + "    ON (t_novedades.ID_EMPRESA = t_empresas.ID_EMPRESA)\n"
                        + "  INNER JOIN t_eps\n"
                        + "    ON (t_novedades.ID_EPS = t_eps.ID_EPS)\n"
                        + "  INNER JOIN t_afp\n"
                        + "    ON (t_novedades.ID_AFP = t_afp.ID_AFP)\n"
                        + "  INNER JOIN t_municipios\n"
                        + "    ON (t_novedades.ID_MUN_NOV = t_municipios.ID_MUN)\n"
                        + "  INNER JOIN t_parentesco\n"
                        + "    ON (t_novedades.ID_PAR_ACU_NOV = t_parentesco.ID_PAR)\n"
                        + "  INNER JOIN t_obra\n"
                        + "    ON (t_novedades.ID_OBRA = t_obra.ID_OBRA)\n"
                        + "  INNER JOIN t_tipo_novedad\n"
                        + "    ON (t_novedades.ID_TIPO = t_tipo_novedad.ID_TIPO)\n"
                        + "WHERE (t_novedades.ID_EMPLEADO = "+this.ced+" AND t_novedades.ID_EMPRESA = "+modelo.getValueAt(empleadores.getSelectedRow(),0)+" AND t_tipo_novedad.NOMBRE_TIPO = '"+modelo.getValueAt(empleadores.getSelectedRow(),2)+"')\n"
                        + "ORDER BY FECHA_INGRESO DESC;");
                    if(r.next()){
                        ret.add(r.getString("ID_EMP"));
                        ret.add(r.getString("ID_EMPRESA"));
                        ret.add(r.getString("FECHA_INGRESO"));
                        ret.add(r.getString("FECHA_RETIRO"));
                        ret.add(r.getString("ID_TIPO"));
                    }
                    con.cerrar();
                } catch (SQLException e) {
                    con.cerrar();
                    e.printStackTrace();
                }
            this.dispose();
            }
        }
    }//GEN-LAST:event_empleadoresKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sel_Empleador_1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sel_Empleador_1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sel_Empleador_1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sel_Empleador_1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sel_Empleador_1_3 dialog = new Sel_Empleador_1_3(new javax.swing.JDialog(), true, new String(), new String());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedula;
    private javax.swing.JTable empleadores;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nom_ap;
    // End of variables declaration//GEN-END:variables

    public ArrayList getRet() {
        return ret;
    }


}
