/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.Edicof.GUI;

import com.jm.Edicof.Clases.Conexion;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Johnnatan
 */
public class View_Info_Socio_Demografico extends javax.swing.JDialog {
String cedula ="";
boolean perm=false;
boolean perm_mun=false;
    /**
     * Creates new form Add_Info_Socio_Demografico
     */
    public View_Info_Socio_Demografico(java.awt.Frame parent, boolean modal, String ced) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        this.cedula=ced;
        ac_dep();
        ac_mun(cb_dep.getSelectedItem().toString());
        ac_barrio(cb_mun.getSelectedItem().toString());
        ac_tip_vivienda();
        ac_area();
        ac_cargo();
        ac_estado();
        ac_niv_acad();
        ac_nacionalidad();
        ac_parentesco();
        perm=true;
        perm_mun=true;
        load_info(this.cedula);
        
    }
    public View_Info_Socio_Demografico(javax.swing.JDialog parent, boolean modal, String ced) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        this.cedula=ced;
        ac_dep();
        ac_mun(cb_dep.getSelectedItem().toString());
        ac_barrio(cb_mun.getSelectedItem().toString());
        ac_tip_vivienda();
        ac_area();
        ac_cargo();
        ac_estado();
        ac_niv_acad();
        ac_nacionalidad();
        ac_parentesco();
        perm=true;
        perm_mun=true;
        load_info(this.cedula);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group_Tiempo_libre = new javax.swing.ButtonGroup();
        Group_ahorro = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cb_est_civil = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cb_num_hijos = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cb_num_pers_cargo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cb_niv = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cb_nacion = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cb_pers_hogar = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cb_pers_aport = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        sp_acueducto = new javax.swing.JCheckBox();
        sp_energia = new javax.swing.JCheckBox();
        sp_gas = new javax.swing.JCheckBox();
        sp_aseo = new javax.swing.JCheckBox();
        sp_alcanarillado = new javax.swing.JCheckBox();
        sp_telefono = new javax.swing.JCheckBox();
        sp_television = new javax.swing.JCheckBox();
        sp_internet = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        pf_cta_ahorro = new javax.swing.JCheckBox();
        pf_credito_formal = new javax.swing.JCheckBox();
        pf_cta_corr = new javax.swing.JCheckBox();
        pf_no = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        fa_a_informal = new javax.swing.JCheckBox();
        fa_bancos = new javax.swing.JCheckBox();
        fa_f_cesantias = new javax.swing.JCheckBox();
        fa_f_empleados = new javax.swing.JCheckBox();
        fa_ninguno = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        rb_ahorro_si = new javax.swing.JRadioButton();
        rb_ahorro_no = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        tl_dep = new javax.swing.JCheckBox();
        tl_ed = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb_parentesco = new javax.swing.JComboBox<>();
        cel_tel_acu = new javax.swing.JTextField();
        nomb_acud = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cel_tel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_mun = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_estrato = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cb_vivienda = new javax.swing.JComboBox<>();
        cb_barrio = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cb_dep = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cb_area = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cb_cargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizar Información Socio Demografica");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal"));

        jLabel3.setText("Estado Civil");

        cb_est_civil.setEnabled(false);

        jLabel4.setText("Numero de hijos");

        cb_num_hijos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_num_hijos.setEnabled(false);

        jLabel13.setText("Personas a cargo");

        cb_num_pers_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_num_pers_cargo.setEnabled(false);

        jLabel14.setText("Nivel Academico");

        cb_niv.setEnabled(false);

        jLabel16.setText("Nacionalidad");

        cb_nacion.setEnabled(false);

        jLabel17.setText("Personas en el hogar");

        cb_pers_hogar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_pers_hogar.setEnabled(false);

        jLabel18.setText("Personas aportan en el hogar");

        cb_pers_aport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_pers_aport.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_num_hijos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_est_civil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_niv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_nacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_num_pers_cargo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_pers_hogar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_pers_aport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_est_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_num_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_niv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_nacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_num_pers_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_pers_hogar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_pers_aport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Servicios Publicos"));

        sp_acueducto.setText("Acueducto");
        sp_acueducto.setEnabled(false);

        sp_energia.setText("Energia");
        sp_energia.setEnabled(false);

        sp_gas.setText("Gas");
        sp_gas.setEnabled(false);

        sp_aseo.setText("Aseo");
        sp_aseo.setEnabled(false);

        sp_alcanarillado.setText("Alcantarillado");
        sp_alcanarillado.setEnabled(false);

        sp_telefono.setText("Telefonia");
        sp_telefono.setEnabled(false);

        sp_television.setText("Television");
        sp_television.setEnabled(false);

        sp_internet.setText("Internet");
        sp_internet.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_aseo)
                    .addComponent(sp_gas)
                    .addComponent(sp_energia)
                    .addComponent(sp_acueducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_internet)
                    .addComponent(sp_television)
                    .addComponent(sp_telefono)
                    .addComponent(sp_alcanarillado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sp_alcanarillado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_television)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_internet))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sp_acueducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_energia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_gas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_aseo)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos financieros"));

        pf_cta_ahorro.setText("Cta ahorros");
        pf_cta_ahorro.setEnabled(false);

        pf_credito_formal.setText("Credito formal");
        pf_credito_formal.setEnabled(false);

        pf_cta_corr.setText("Cta corriente");
        pf_cta_corr.setEnabled(false);

        pf_no.setText("No ha tenido aceso");
        pf_no.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pf_no)
                    .addComponent(pf_cta_corr)
                    .addComponent(pf_credito_formal)
                    .addComponent(pf_cta_ahorro))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(pf_cta_ahorro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_credito_formal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_cta_corr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_no)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Fuente ahorros"));

        fa_a_informal.setText("Ahorro informal");
        fa_a_informal.setEnabled(false);

        fa_bancos.setText("Bancos");
        fa_bancos.setEnabled(false);

        fa_f_cesantias.setText("Fondo cesantias");
        fa_f_cesantias.setEnabled(false);

        fa_f_empleados.setText("Fondo empleados");
        fa_f_empleados.setEnabled(false);

        fa_ninguno.setText("Ninguno");
        fa_ninguno.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fa_ninguno)
                    .addComponent(fa_f_empleados)
                    .addComponent(fa_f_cesantias)
                    .addComponent(fa_bancos)
                    .addComponent(fa_a_informal))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fa_a_informal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fa_bancos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fa_f_cesantias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fa_f_empleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fa_ninguno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Ahorro"));

        Group_ahorro.add(rb_ahorro_si);
        rb_ahorro_si.setText("Si");
        rb_ahorro_si.setEnabled(false);

        Group_ahorro.add(rb_ahorro_no);
        rb_ahorro_no.setText("No");
        rb_ahorro_no.setEnabled(false);
        rb_ahorro_no.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_ahorro_noStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_ahorro_si)
                .addGap(18, 18, 18)
                .addComponent(rb_ahorro_no)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_ahorro_si)
                    .addComponent(rb_ahorro_no))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tiempo Libre"));

        tl_dep.setText("Deporte");
        tl_dep.setEnabled(false);
        tl_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tl_depActionPerformed(evt);
            }
        });

        tl_ed.setText("Educacion");
        tl_ed.setEnabled(false);
        tl_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tl_edActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tl_ed)
                    .addComponent(tl_dep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tl_dep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tl_ed)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Acudiente"));

        jLabel6.setText("Nombre");

        jLabel7.setText("Cel/Tel");

        jLabel8.setText("Parentesco");

        cb_parentesco.setEnabled(false);

        cel_tel_acu.setEditable(false);
        cel_tel_acu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cel_tel_acu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cel_tel_acuKeyTyped(evt);
            }
        });

        nomb_acud.setEditable(false);
        nomb_acud.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomb_acud)
                    .addComponent(cel_tel_acu)
                    .addComponent(cb_parentesco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomb_acud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cel_tel_acu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_1.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubicacion"));

        jLabel1.setText("Direccion");

        direccion.setEditable(false);
        direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Cel/Tel");

        cel_tel.setEditable(false);
        cel_tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cel_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cel_telKeyTyped(evt);
            }
        });

        jLabel10.setText("Barrio");

        cb_mun.setEnabled(false);
        cb_mun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_munItemStateChanged(evt);
            }
        });

        jLabel9.setText("Ciudad Residencia");

        jLabel12.setText("Estrato");

        cb_estrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..", "1", "2", "3", "4", "5", "6" }));
        cb_estrato.setEnabled(false);

        jLabel15.setText("Tipo Vivienda");

        cb_vivienda.setEnabled(false);

        cb_barrio.setEnabled(false);

        jLabel11.setText("Departamento de Residencia");

        cb_dep.setEnabled(false);
        cb_dep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_depItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_mun, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_barrio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cel_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cb_estrato, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(cb_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cel_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_estrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Información Laboral"));

        jLabel5.setText("Area de trabajo");

        cb_area.setEnabled(false);

        jLabel19.setText("Cargo");

        cb_cargo.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_area, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_ahorro_noStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_ahorro_noStateChanged
        // TODO add your handling code here:
        if (rb_ahorro_no.isSelected()) {
            fa_ninguno.setSelected(true);
            fa_a_informal.setSelected(false);
            fa_bancos.setSelected(false);
            fa_f_cesantias.setSelected(false);
            fa_f_empleados.setSelected(false);
        }
    }//GEN-LAST:event_rb_ahorro_noStateChanged

    private void cb_depItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_depItemStateChanged
        // TODO add your handling code here:
        if (perm) {
            //perm_mun=false;
            ac_mun(cb_dep.getSelectedItem().toString());
            //perm_mun=true;
        }
        
    }//GEN-LAST:event_cb_depItemStateChanged

    private void cb_munItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_munItemStateChanged
        // TODO add your handling code here:
        if (perm_mun) {
            if (cb_mun.getSelectedItem()!=null) {
                ac_barrio(cb_mun.getSelectedItem().toString());
            }
            
            
        }
        
    }//GEN-LAST:event_cb_munItemStateChanged

    private void cel_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cel_telKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if (a!=KeyEvent.VK_MINUS) {
            if(!(a>=KeyEvent.VK_0 && a<=KeyEvent.VK_9)) {
                evt.consume();
            }
        }
        
    }//GEN-LAST:event_cel_telKeyTyped

    private void cel_tel_acuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cel_tel_acuKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if (a!=KeyEvent.VK_MINUS) {
            if(!(a>=KeyEvent.VK_0 && a<=KeyEvent.VK_9)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_cel_tel_acuKeyTyped

    private void tl_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tl_depActionPerformed
        // TODO add your handling code here:
        if (!tl_dep.isSelected() & !tl_ed.isSelected()) {
            tl_dep.setSelected(true);
        }
    }//GEN-LAST:event_tl_depActionPerformed

    private void tl_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tl_edActionPerformed
        // TODO add your handling code here:
        if (!tl_dep.isSelected() & !tl_ed.isSelected()) {
            tl_ed.setSelected(true);
        }
    }//GEN-LAST:event_tl_edActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Info_Socio_Demografico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Info_Socio_Demografico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Info_Socio_Demografico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Info_Socio_Demografico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View_Info_Socio_Demografico dialog = new View_Info_Socio_Demografico(new javax.swing.JFrame(), true, new String());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Group_Tiempo_libre;
    private javax.swing.ButtonGroup Group_ahorro;
    private javax.swing.JComboBox<String> cb_area;
    private javax.swing.JComboBox<String> cb_barrio;
    private javax.swing.JComboBox<String> cb_cargo;
    private javax.swing.JComboBox<String> cb_dep;
    private javax.swing.JComboBox<String> cb_est_civil;
    private javax.swing.JComboBox<String> cb_estrato;
    private javax.swing.JComboBox<String> cb_mun;
    private javax.swing.JComboBox<String> cb_nacion;
    private javax.swing.JComboBox<String> cb_niv;
    private javax.swing.JComboBox<String> cb_num_hijos;
    private javax.swing.JComboBox<String> cb_num_pers_cargo;
    private javax.swing.JComboBox<String> cb_parentesco;
    private javax.swing.JComboBox<String> cb_pers_aport;
    private javax.swing.JComboBox<String> cb_pers_hogar;
    private javax.swing.JComboBox<String> cb_vivienda;
    private javax.swing.JTextField cel_tel;
    private javax.swing.JTextField cel_tel_acu;
    private javax.swing.JTextField direccion;
    private javax.swing.JCheckBox fa_a_informal;
    private javax.swing.JCheckBox fa_bancos;
    private javax.swing.JCheckBox fa_f_cesantias;
    private javax.swing.JCheckBox fa_f_empleados;
    private javax.swing.JCheckBox fa_ninguno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField nomb_acud;
    private javax.swing.JCheckBox pf_credito_formal;
    private javax.swing.JCheckBox pf_cta_ahorro;
    private javax.swing.JCheckBox pf_cta_corr;
    private javax.swing.JCheckBox pf_no;
    private javax.swing.JRadioButton rb_ahorro_no;
    private javax.swing.JRadioButton rb_ahorro_si;
    private javax.swing.JCheckBox sp_acueducto;
    private javax.swing.JCheckBox sp_alcanarillado;
    private javax.swing.JCheckBox sp_aseo;
    private javax.swing.JCheckBox sp_energia;
    private javax.swing.JCheckBox sp_gas;
    private javax.swing.JCheckBox sp_internet;
    private javax.swing.JCheckBox sp_telefono;
    private javax.swing.JCheckBox sp_television;
    private javax.swing.JCheckBox tl_dep;
    private javax.swing.JCheckBox tl_ed;
    // End of variables declaration//GEN-END:variables
public final void ac_dep(){
    cb_dep.removeAllItems();
    cb_dep.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_departamentos ORDER BY NOMBRE_DEP ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_DEP");
            cb_dep.addItem(str);
            
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }

}
public final void ac_mun(String dep){
    cb_mun.removeAllItems();
    if (dep.equals("Seleccione..")) {
        cb_mun.addItem("Seleccione..");
    } else {
        cb_mun.addItem("Seleccione..");
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try{
            r = con.s.executeQuery ("SELECT *\n" +
                                    "FROM\n" +
                                    "    t_municipios\n" +
                                    "    INNER JOIN t_departamentos \n" +
                                    "        ON (t_municipios.ID_DEP = t_departamentos.ID_DEP) WHERE NOMBRE_DEP = '"+dep+"' ORDER BY NOMBRE_MUN ASC;");
            while(r.next()){
                String str=r.getString("NOMBRE_MUN");
                cb_mun.addItem(str);
            }
            con.cerrar();
        }catch(SQLException j){
            con.cerrar();
            j.printStackTrace();
            JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

}
public final void ac_barrio(String mun){
    cb_barrio.removeAllItems();
    if (mun.equals("Seleccione..")) {
        cb_barrio.addItem("Seleccione..");
    } else {
        cb_barrio.addItem("Seleccione..");
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try{
            r = con.s.executeQuery ("SELECT *\n" +
                                    "FROM\n" +
                                    "    t_barrio\n" +
                                    "    INNER JOIN t_municipios \n" +
                                    "        ON (t_municipios.ID_MUN = t_barrio.ID_MUN_BARRIO) WHERE NOMBRE_MUN = '"+mun+"' ORDER BY NOMBRE_BARRIO ASC;");
            while(r.next()){
                String str=r.getString("NOMBRE_BARRIO");
                cb_barrio.addItem(str);
            }
            con.cerrar();
        }catch(SQLException j){
            con.cerrar();
            j.printStackTrace();
            JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

}
public final void ac_estado(){
    cb_est_civil.removeAllItems();
    cb_est_civil.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_estado_civil\n" +
                                "    ORDER BY NOMBRE_ESTADO ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_ESTADO");
            cb_est_civil.addItem(str);
            
            
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public final void ac_area(){
    cb_area.removeAllItems();
    cb_area.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_actividades\n" +
                                "    ORDER BY NOMBRE_ACTIVIDAD ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_ACTIVIDAD");
            cb_area.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public final void ac_cargo(){
    cb_cargo.removeAllItems();
    cb_cargo.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_cargo\n" +
                                "    ORDER BY NOMBRE_CARGO ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_CARGO");
            cb_cargo.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public final void ac_niv_acad(){
    cb_niv.removeAllItems();
    cb_niv.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_nivel_academico\n" +
                                "ORDER BY NOMBRE_NIVEL ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_NIVEL");
            cb_niv.addItem(str);
            
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public final void ac_tip_vivienda(){
    cb_vivienda.removeAllItems();
    cb_vivienda.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_tipo_vivienda\n" +
                                "ORDER BY NOMBRE_TIPO_VIVIENDA ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_TIPO_VIVIENDA");
            cb_vivienda.addItem(str);
            
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public final void ac_nacionalidad(){
    cb_nacion.removeAllItems();
    cb_nacion.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_nacionalidad\n" +
                                "ORDER BY NOMBRE_NACION ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_NACION");
            cb_nacion.addItem(str);
            
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        j.printStackTrace();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public final void ac_parentesco(){
    cb_parentesco.removeAllItems();
    cb_parentesco.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    t_parentesco\n" +
                                "ORDER BY NOMBRE_PAR ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_PAR");
            cb_parentesco.addItem(str);
            
        }
        con.cerrar();
    }catch(SQLException j){
        j.printStackTrace();
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
public boolean chech_char(String s, String c){
    //boolean ret=false;
    char []char_s=s.toCharArray();
    char []char_c=c.toCharArray();  
    for (int i = 0; i < char_s.length; i++) {
        for (int j = 0; j < char_c.length; j++) {
            if (char_s[i]==char_c[j]) {
                return false;
            }
        }
    }
    return true;
}
public boolean check_field_dir (Object field){
boolean ret=false;
    if (field!=null) {
        if (chech_char(field.toString().trim(),"'$%&()=?¡¿/*+[]{};:<>,")) {
            if (!field.toString().equals("")) {
               ret=true;
            }
        }
    }

return ret;
}
public boolean check_field (Object field){
boolean ret=false;
    if (field!=null) {
        if (!field.toString().trim().equals("")) {
            if (chech_char(field.toString().trim(),"'$%&()=?¡¿/*+[]{};:<>,")) {
                if (!field.toString().equals("")) {
                   ret=true;
                }
            } 
        }
    }
return ret;
}
public boolean check_tel_field (Object field){
boolean ret=false;
    if (field!=null) {
        if (!field.toString().trim().equals("")) {
            if (chech_char(field.toString().trim(),"'$%&()=?¡¿/*+[]{};:<>,")) {
                if (!field.toString().equals("")) {
                    int count=0;
                    for (int i = 0; i < field.toString().length(); i++) {
                        if ((int)field.toString().charAt(i)>=48 & (int)field.toString().charAt(i)<=57) {
                            count++;
                        }
                    }
                    if (count>=7) {
                        ret=true;
                    } else {
                        ret=false;
                    }
                }
            } 
        }
    }
return ret;
}
public void load_info(String ced){
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT *\n" +
                                "FROM\n" +
                                "    `t_info_sociodemografica`\n" +
                                "    INNER JOIN `t_estado_civil` \n" +
                                "        ON (`t_info_sociodemografica`.`ID_ESTADO_CIVIL_EMP` = `t_estado_civil`.`ID_ESTADO`)\n" +
                                "    INNER JOIN `t_cargo` \n" +
                                "        ON (`t_info_sociodemografica`.`ID_CARGO` = `t_cargo`.`ID_CARGO`)\n" +
                                "    INNER JOIN `t_actividades` \n" +
                                "        ON (`t_info_sociodemografica`.`ID_AREA_TRABAJO_EMP` = `t_actividades`.`ID_ACTIVIDAD`)\n" +
                                "    INNER JOIN `t_parentesco` \n" +
                                "        ON (`t_info_sociodemografica`.`ID_PAR_ACU_EMP` = `t_parentesco`.`ID_PAR`)\n" +
                                "    INNER JOIN `t_barrio` \n" +
                                "        ON (`t_info_sociodemografica`.`ID_BARRIO` = `t_barrio`.`ID_BARRIO`)\n" +
                                "    INNER JOIN `t_municipios` \n" +
                                "        ON (`t_info_sociodemografica`.`ID_MUN_RES_EMP` = `t_municipios`.`ID_MUN`)\n" +
                                "    INNER JOIN `t_departamentos` \n" +
                                "        ON (`t_municipios`.`ID_DEP` = `t_departamentos`.`ID_DEP`)\n" +
                                "    INNER JOIN `t_nivel_academico` \n" +
                                "        ON (`t_info_sociodemografica`.`ID_NIV_ACAD_EMP` = `t_nivel_academico`.`ID_NIVEL`)\n" +
                                "    INNER JOIN `t_tipo_vivienda` \n" +
                                "        ON (`t_info_sociodemografica`.`ID_TIP_VIV_EMP` = `t_tipo_vivienda`.`ID_TIPO_VIVIENDA`)\n" +
                                "    INNER JOIN `t_nacionalidad` \n" +
                                "        ON (`t_info_sociodemografica`.`ID_NACION_EMP` = `t_nacionalidad`.`ID_NACION`)\n" +
                                "       WHERE ID_EMP = "+ced+";");
        if(r.next()){
            direccion.setText(r.getString("DIRECCION_EMP"));
            cel_tel.setText(r.getString("TEL_CEL_EMP"));
            cb_dep.setSelectedItem(r.getString("NOMBRE_DEP"));
            cb_mun.setSelectedItem(r.getString("NOMBRE_MUN"));
            cb_barrio.setSelectedItem(r.getString("NOMBRE_BARRIO"));
            cb_estrato.setSelectedItem(r.getString("ESTRATO_EMP"));
            cb_vivienda.setSelectedItem(r.getString("NOMBRE_TIPO_VIVIENDA"));
            cb_area.setSelectedItem(r.getString("NOMBRE_ACTIVIDAD"));
            cb_cargo.setSelectedItem(r.getString("NOMBRE_CARGO"));
            cb_est_civil.setSelectedItem(r.getString("NOMBRE_ESTADO"));
            cb_num_hijos.setSelectedItem(r.getString("NUM_HIJOS_EMP"));
            cb_niv.setSelectedItem(r.getString("NOMBRE_NIVEL"));
            cb_nacion.setSelectedItem(r.getString("NOMBRE_NACION"));
            cb_num_pers_cargo.setSelectedItem(r.getString("PER_CARGO_EMP"));
            cb_pers_hogar.setSelectedItem(r.getString("PERS_HOGAR_EMP"));
            cb_pers_aport.setSelectedItem(r.getString("PERS_AP_HOGAR_EMP"));
            nomb_acud.setText(r.getString("NOMBRE_ACUDIENTE_EMP"));
            cel_tel_acu.setText(r.getString("TEL_CEL_ACU_EMP"));
            cb_parentesco.setSelectedItem(r.getString("NOMBRE_PAR"));
            switch(r.getString("AHORRO_EMP")){
                case "SI": rb_ahorro_si.setSelected(true);
                break;
                case "NO": rb_ahorro_no.setSelected(true);
                break;
            }
        }
        r = con.s.executeQuery ("SELECT * FROM `t_rel_t_prod_fin` WHERE ID_EMP = "+ced);
        while (r.next()) {
           switch(r.getInt("ID_PROD_FIN")){
               case 1: pf_cta_ahorro.setSelected(true);
               break;
               case 2: pf_credito_formal.setSelected(true);
               break;
               case 3: pf_cta_corr.setSelected(true);
               break;
               case 4: pf_no.setSelected(true);
               break;
           }
        }
        r = con.s.executeQuery ("SELECT * FROM `t_rel_t_tiempo_libre` WHERE ID_EMP = "+ced);
        while(r.next()){
            switch(r.getInt("ID_TIEMP_LIBRE")){
               case 1: tl_dep.setSelected(true);
               break;
               case 2: tl_ed.setSelected(true);
               break;
           }
        }
        r = con.s.executeQuery ("SELECT * FROM `t_rel_serv_public` WHERE ID_EMP = "+ced);
        while(r.next()){
            switch(r.getInt("ID_SERV_PUB")){
               case 1: sp_acueducto.setSelected(true);
               break;
               case 2: sp_energia.setSelected(true);
               break;
               case 3: sp_gas.setSelected(true);
               break;
               case 4: sp_aseo.setSelected(true);
               break;
               case 5: sp_alcanarillado.setSelected(true);
               break;
               case 6: sp_telefono.setSelected(true);
               break;
               case 7: sp_television.setSelected(true);
               break;
               case 8: sp_internet.setSelected(true);
               break;
           }
        }
        r = con.s.executeQuery ("SELECT * FROM `t_rel_fte_ahorro` WHERE ID_EMP = "+ced);
        while(r.next()){
            switch(r.getInt("ID_FTE_AHORRO")){
               case 1: fa_a_informal.setSelected(true);
               break;
               case 2: fa_bancos.setSelected(true);
               break;
               case 3: fa_f_cesantias.setSelected(true);
               break;
               case 4: fa_f_empleados.setSelected(true);
               break;
               case 5: fa_ninguno.setSelected(true);
               break;
           }
        }
        con.cerrar();
    }catch(SQLException j){
        j.printStackTrace();
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
}
