/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jm.outhelp.GUI;

import com.jm.outhelp.GUI.*;
import com.jm.outhelp.Clases.AutoCompletion;
import com.jm.outhelp.Clases.Conexion;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Event;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author ADMIN
 */
public class Add_Empresa extends javax.swing.JDialog {
    TextAutoCompleter tac_nit = null;
 
    /**
     * Creates new form Add_Empleado
     * @param parent
     * @param modal
     */
    public Add_Empresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        init();
        ac_nit();
        ac_arl();
        ac_ccf();
        ac_act();
        tac_nit.setMode(0);
        InputMap map1 = nit.getInputMap(nit.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
    }
    public Add_Empresa(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/group_gear.png")));
        init();
        ac_nit();
        ac_arl();
        ac_ccf();
        tac_nit.setMode(0);
        InputMap map1 = nit.getInputMap(nit.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
    }
    public void init(){
        tac_nit = new TextAutoCompleter(nit, new AutoCompleterCallback() {
        @Override
        public void callback(Object selectedItem) {
            load_data(selectedItem.toString());
        }
        });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre_empresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nit = new javax.swing.JTextField();
        cb_arl = new javax.swing.JComboBox<>();
        add_arl = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cb_ccf = new javax.swing.JComboBox<>();
        add_ccf = new javax.swing.JButton();
        edd_arl = new javax.swing.JButton();
        add_ccf1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cb_actividad = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        correo_interno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        correo_1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        correo_2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        correo_3 = new javax.swing.JTextField();
        sel_1 = new javax.swing.JCheckBox();
        sel_3 = new javax.swing.JCheckBox();
        sel_2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        sel_int = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        representante = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefonos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Empresa");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de la empresa"));

        jLabel1.setText("Nombre Empresa");

        nombre_empresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_empresaKeyTyped(evt);
            }
        });

        jLabel2.setText("NIT");

        nit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nitKeyTyped(evt);
            }
        });

        AutoCompletion.enable(cb_arl);
        cb_arl.setEditable(true);

        add_arl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/link_add.png"))); // NOI18N
        add_arl.setToolTipText("Agregar ARL");
        add_arl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_arlActionPerformed(evt);
            }
        });

        jLabel9.setText("ARL");

        jLabel21.setText("CCF");

        AutoCompletion.enable(cb_ccf);
        cb_ccf.setEditable(true);

        add_ccf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart_add.png"))); // NOI18N
        add_ccf.setToolTipText("Agregar CCF");
        add_ccf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ccfActionPerformed(evt);
            }
        });

        edd_arl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/link_edit.png"))); // NOI18N
        edd_arl.setToolTipText("Editar ARL");
        edd_arl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edd_arlActionPerformed(evt);
            }
        });

        add_ccf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart_half.png"))); // NOI18N
        add_ccf1.setToolTipText("Editar CCF");
        add_ccf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ccf1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Actividad");

        cb_actividad.setEditable(true);
        AutoCompletion.enable(cb_actividad);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel21))
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_actividad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_ccf, 0, 213, Short.MAX_VALUE)
                            .addComponent(cb_arl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(add_ccf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_ccf1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(add_arl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edd_arl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(add_arl)
                    .addComponent(cb_arl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edd_arl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(add_ccf)
                    .addComponent(cb_ccf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_ccf1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accept_1.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_1.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de correo"));

        jLabel3.setText("Correo interno");

        correo_interno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("Correo contratista 1");

        correo_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Correo contratista 2");

        correo_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Correo contratista 3");

        correo_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setText("Sel.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correo_3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo_2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(correo_interno)
                        .addComponent(correo_1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(sel_1)
                        .addComponent(sel_2)
                        .addComponent(sel_3))
                    .addComponent(sel_int))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(correo_interno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(sel_int))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(correo_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sel_1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(correo_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(sel_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(correo_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(sel_3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos adicionales"));

        jLabel8.setText("Representante legal");

        representante.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setText("Telefonos");

        telefonos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefonos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telefonos, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(representante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(telefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int id_arl = 0;
        int id_ccf = 0;
        int id_act = 0;
        if (!nit.getText().equals("")) {
            if (!nombre_empresa.getText().equals("")) {
                if (!cb_arl.getSelectedItem().equals("Seleccione..")) {
                    if (!cb_ccf.getSelectedItem().equals("Seleccione..")) {
                        if (!cb_actividad.getSelectedItem().equals("Seleccione..")) {
                            if (check_mail(correo_interno.getText())) {
                                if (check_mail(correo_1.getText())) {
                                    if (check_mail(correo_2.getText())) {
                                        if (check_mail(correo_3.getText())) {
                                            if (sel_int.isSelected() | sel_1.isSelected() | sel_2.isSelected() | sel_3.isSelected()) {
                                                if (!(correo_interno.getText().equals("") & sel_int.isSelected())) {
                                                    if (!(correo_1.getText().equals("") & sel_1.isSelected())) {
                                                        if (!(correo_2.getText().equals("") & sel_2.isSelected())) {
                                                            if (!(correo_3.getText().equals("") & sel_3.isSelected())) {
                                                                Conexion con = new Conexion();
                                                                con.conexion();
                                                                ResultSet r;
                                                                try {
                                                                    r = con.s.executeQuery ("SELECT * FROM `t_empresas` WHERE ID_EMPRESA = '"+nit.getText()+"'");
                                                                    if(r.next()){
                                                                        JOptionPane.showMessageDialog(this,"La empresa que intenta ingresar ya existe","Error",JOptionPane.ERROR_MESSAGE);
                                                                    }
                                                                    else{
                                                                        int conf = JOptionPane.showConfirmDialog(this,"Esta seguro que desea continuar?","Confirmación",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
                                                                        if (conf == JOptionPane.YES_OPTION) {
                                                                            r = con.s.executeQuery ("SELECT * FROM `t_arl` WHERE (NOMBRE_ARL ='"+cb_arl.getSelectedItem().toString()+"');");
                                                                            if(r.next()){
                                                                                id_arl=r.getInt("ID_ARL");    
                                                                            }
                                                                            r = con.s.executeQuery ("SELECT * FROM `t_ccf` WHERE (NOMBRE_CCF ='"+cb_ccf.getSelectedItem().toString()+"');");
                                                                            if(r.next()){
                                                                                id_ccf=r.getInt("ID_CCF");    
                                                                            }
                                                                            r = con.s.executeQuery ("SELECT * FROM `t_actividades` WHERE (NOMBRE_ACTIVIDAD ='"+cb_actividad.getSelectedItem().toString()+"');");
                                                                            if(r.next()){
                                                                                id_act=r.getInt("ID_ACTIVIDAD");    
                                                                            }

                                                                            con.s.executeUpdate("INSERT INTO `t_empresas`(`ID_EMPRESA`, `NOMBRE_EMPRESA`, `ID_ARL`, `ID_CCF`, `CORREO_INTERNO`, `CORREO_CONTRATISTA_1`, `CORREO_CONTRATISTA_2`, `CORREO_CONTRATISTA_3`, `ENABLE_INTERNO`, `ENABLE_1`, `ENABLE_2`, `ENABLE_3`, `REPRESENTANTE_LEGAL`, `TELEFONOS`, `ID_ACTIVIDAD`) VALUES ('"+nit.getText().toUpperCase().trim()+"','"+nombre_empresa.getText().toUpperCase().trim()+"',"+id_arl+","+id_ccf+",'"+correo_interno.getText()+"','"+correo_1.getText()+"','"+correo_2.getText()+"','"+correo_3.getText()+"',"+bool_to_int(sel_int.isSelected())+","+bool_to_int(sel_1.isSelected())+","+bool_to_int(sel_2.isSelected())+","+bool_to_int(sel_3.isSelected())+",'"+representante.getText()+"','"+telefonos.getText()+"',"+id_act+")");
                                                                            //con.s.executeUpdate("INSERT INTO `t_empresas`(`ID_EMPRESA`, `NOMBRE_EMPRESA`, `ID_ARL`, `ID_CCF`) VALUES ('"+nit.getText().toUpperCase().trim()+"','"+nombre_empresa.getText().toUpperCase().trim()+"',"+id_arl+","+id_ccf+")");
                                                                            JOptionPane.showMessageDialog(this,"La empresa fue ingresada correctamente","Información",JOptionPane.INFORMATION_MESSAGE);
                                                                            con.cerrar();
                                                                            this.dispose();
                                                                        }
                                                                    }
                                                                    con.cerrar();
                                                                } catch (SQLException | HeadlessException e) {
                                                                    con.cerrar();
                                                                    e.printStackTrace();
                                                                    JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
                                                                }
                                                            }else{
                                                                sel_3.requestFocus();
                                                                JOptionPane.showMessageDialog(this,"No se debe seleccionar un correo no valido","Error",JOptionPane.ERROR_MESSAGE);
                                                            }
                                                        }else{
                                                            sel_2.requestFocus();
                                                            JOptionPane.showMessageDialog(this,"No se debe seleccionar un correo no valido","Error",JOptionPane.ERROR_MESSAGE);
                                                        }
                                                    }else{
                                                        sel_1.requestFocus();
                                                        JOptionPane.showMessageDialog(this,"No se debe seleccionar un correo no valido","Error",JOptionPane.ERROR_MESSAGE);
                                                    }
                                                }else{
                                                    sel_int.requestFocus();
                                                    JOptionPane.showMessageDialog(this,"No se debe seleccionar un correo no valido","Error",JOptionPane.ERROR_MESSAGE);
                                                }
                                            }else{
                                                JOptionPane.showMessageDialog(this,"Seleccione al menos una direccion de correo para el envio automatico de informes.","Error",JOptionPane.ERROR_MESSAGE);
                                            }
                                        }else{
                                            correo_3.requestFocus();
                                            JOptionPane.showMessageDialog(this,"Verifique el correo alterno 3 de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                        }
                                    }else{
                                        correo_2.requestFocus();
                                        JOptionPane.showMessageDialog(this,"Verifique el correo alterno 2 de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                    }
                                }else{
                                    correo_1.requestFocus();
                                    JOptionPane.showMessageDialog(this,"Verifique el correo alterno 1 de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                                }
                            }else{
                                correo_interno.requestFocus();
                                JOptionPane.showMessageDialog(this,"Verifique el correo interno de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                            }
                        }else{
                            cb_actividad.requestFocus();
                            JOptionPane.showMessageDialog(this,"Seleccione la Actividad de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        
                        
                        
                        
                    }else {
                        cb_ccf.requestFocus();
                        JOptionPane.showMessageDialog(this,"Seleccione la CCF de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }else {
                    cb_arl.requestFocus();
                    JOptionPane.showMessageDialog(this,"Seleccione la ARL de la empresa","Error",JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,"Digite el nombre de la empresa","Error",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,"Digite el NIT de la empresa","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
        int a = evt.getKeyCode();
        
        if (a==KeyEvent.VK_CAPS_LOCK) {
            nombre_empresa.setToolTipText("Caps Lock ON");
        }else{
            nombre_empresa.setToolTipText("Caps Lock OFF");
        }
    }//GEN-LAST:event_formKeyTyped

    private void add_ccf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ccf1ActionPerformed
        // TODO add your handling code here:
        Edd_CCF edd_ccf = new Edd_CCF(this, true);
        edd_ccf.setLocationRelativeTo(this);
        edd_ccf.setVisible(true);
    }//GEN-LAST:event_add_ccf1ActionPerformed

    private void edd_arlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edd_arlActionPerformed
        // TODO add your handling code here:
        Edd_ARL edd_arl = new Edd_ARL(this, true);
        edd_arl.setLocationRelativeTo(this);
        edd_arl.setVisible(true);
    }//GEN-LAST:event_edd_arlActionPerformed

    private void add_ccfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ccfActionPerformed
        // TODO add your handling code here:
        Add_CCF add_ccf = new Add_CCF(this, true);
        add_ccf.setLocationRelativeTo(this);
        add_ccf.setVisible(true);
    }//GEN-LAST:event_add_ccfActionPerformed

    private void add_arlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_arlActionPerformed
        // TODO add your handling code here:
        Add_ARL add_arl = new Add_ARL(this, true);
        add_arl.setLocationRelativeTo(this);
        add_arl.setVisible(true);
    }//GEN-LAST:event_add_arlActionPerformed

    private void nitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nitKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if(a!=KeyEvent.VK_MINUS){
            if(!(a>=KeyEvent.VK_0 && a<=KeyEvent.VK_9)) {
                evt.consume();
            }
        }
        if(nit.getText().length()>15){
            evt.consume();
        }
    }//GEN-LAST:event_nitKeyTyped

    private void nombre_empresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_empresaKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        a = Character.toUpperCase(a);
        System.out.println(evt.getKeyCode());
        if(!(a>=KeyEvent.VK_A && a<=KeyEvent.VK_Z) & a!=KeyEvent.VK_SPACE & a!=209) {
            evt.consume();
        }
        if(nombre_empresa.getText().length()>50){
            evt.consume();
        }

    }//GEN-LAST:event_nombre_empresaKeyTyped

    private void telefonosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonosKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if(a!=KeyEvent.VK_MINUS){
            if(!(a>=KeyEvent.VK_0 && a<=KeyEvent.VK_9)) {
                evt.consume();
            }
        }

    }//GEN-LAST:event_telefonosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add_Empresa dialog = new Add_Empresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_arl;
    private javax.swing.JButton add_ccf;
    private javax.swing.JButton add_ccf1;
    private javax.swing.JComboBox<String> cb_actividad;
    private javax.swing.JComboBox<String> cb_arl;
    private javax.swing.JComboBox<String> cb_ccf;
    private javax.swing.JTextField correo_1;
    private javax.swing.JTextField correo_2;
    private javax.swing.JTextField correo_3;
    private javax.swing.JTextField correo_interno;
    private javax.swing.JButton edd_arl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private static javax.swing.JTextField nit;
    private static javax.swing.JTextField nombre_empresa;
    private javax.swing.JTextField representante;
    private javax.swing.JCheckBox sel_1;
    private javax.swing.JCheckBox sel_2;
    private javax.swing.JCheckBox sel_3;
    private javax.swing.JCheckBox sel_int;
    private javax.swing.JTextField telefonos;
    // End of variables declaration//GEN-END:variables
public void ac_nit(){
    tac_nit.removeAllItems();
    tac_nit.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_EMPRESAS ORDER BY ID_EMPRESA ASC;");
        while(r.next()){
            String str=r.getString("ID_EMPRESA");
            tac_nit.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}    
public void load_data(String nit){
    if (!nit.equals("Seleccione..")) {
        Conexion con = new Conexion();
        con.conexion();
        ResultSet r;
        try {
            r = con.s.executeQuery ("SELECT * FROM `t_empresas` WHERE ID_EMPRESA = '"+nit+"'");
            if (r.next()) {
                nombre_empresa.setText(r.getString("NOMBRE_EMPRESA"));
            }
            con.cerrar();
        }catch(SQLException j){
            con.cerrar();
            j.printStackTrace();
            JOptionPane.showMessageDialog(this,j,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    else{
        nombre_empresa.setText("");
        
    }
}
public void ac_arl(){
    cb_arl.removeAllItems();
    cb_arl.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_ARL ORDER BY NOMBRE_ARL ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_ARL");
            cb_arl.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }

}
public void ac_ccf(){
    cb_ccf.removeAllItems();
    cb_ccf.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_CCF ORDER BY NOMBRE_CCF ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_CCF");
            cb_ccf.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }

}
public boolean check_mail(String mail){
boolean ret=false;
    if (!mail.equals("")) {
        if (mail.contains("@") & count_char(mail, '@')==1) {
            return true;
        }
    }else{
        return true;
    }
return ret;
}
public int count_char(String str, char c){
    String pr=str.trim();
    char _toCompare=c;
    int veces=0;
    char []caracteres=pr.toCharArray();
    for(int i=0;i<=caracteres.length-1;i++){
        if(_toCompare ==caracteres[i]){
                veces++;
        }
}
    return veces;
}
public int bool_to_int(boolean b){
    if (b) {
        return 1;
    }else{
        return 0;
    }
}
public void ac_act(){
    cb_actividad.removeAllItems();
    cb_actividad.addItem("Seleccione..");
    Conexion con = new Conexion();
    con.conexion();
    ResultSet r;
    try{
        r = con.s.executeQuery ("SELECT * FROM T_ACTIVIDADES ORDER BY NOMBRE_ACTIVIDAD ASC;");
        while(r.next()){
            String str=r.getString("NOMBRE_ACTIVIDAD");
            cb_actividad.addItem(str);
        }
        con.cerrar();
    }catch(SQLException j){
        con.cerrar();
        JOptionPane.showMessageDialog(null,j,"Error",JOptionPane.ERROR_MESSAGE);
    }
}  
}
